import BatteryServices from "./components/BatteryServices";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Battery Services | Everything Auto - Franklin Square",
  description:
    "Expert car battery testing, replacement, and charging system diagnostics in Franklin Square and Long Island. Stay powered with professional auto battery services.",
  keywords: [
    "car battery replacement",
    "auto battery testing",
    "vehicle charging system repair",
    "alternator testing service",
    "starter motor diagnostics",
    "battery maintenance Franklin Square",
    "auto electrical repair",
    "car battery installation",
    "car battery inspection",
    "vehicle power system check",
    "Long Island car battery service",
    "battery voltage testing",
    "battery corrosion cleaning",
    "car not starting help",
    "dead battery replacement",
    "jump start service near me",
    "car battery load test",
    "auto alternator repair",
    "car starter issues",
    "vehicle battery health check",
    "best car battery shop Long Island",
    "battery connection repair",
    "car electrical diagnostics",
    "auto battery charging system test",
    "battery drain test",
    "car alternator replacement",
    "car starter motor repair",
    "vehicle electrical system inspection",
    "car won’t start battery problem",
    "car battery replacement near me",
    "free battery testing Franklin Square",
    "auto repair electrical service",
    "car charging system analysis",
    "alternator belt replacement",
    "car electrical fault diagnostics",
    "starter relay replacement",
    "battery cable corrosion repair",
    "battery terminal cleaning",
    "battery voltage drop test",
    "battery replacement Franklin Square",
    "automotive electrical technician",
    "vehicle power loss diagnosis",
    "battery installation Long Island",
    "car power system repair",
    "alternator output testing",
    "battery efficiency check",
    "car starting issue fix",
    "battery life expectancy check",
    "auto alternator and starter repair",
    "battery and charging diagnostics",
    "auto electrical expert Franklin Square",
    "vehicle voltage regulator testing",
    "charging system maintenance",
    "car power issue diagnosis",
    "auto battery replacement shop",
    "car ignition power issue",
    "vehicle alternator rebuild",
    "battery upgrade for vehicles",
    "car won’t crank fix",
    "automotive starter replacement",
    "auto power issue troubleshooting",
    "vehicle electrical wiring fix",
    "battery inspection Long Island",
    "best battery service Franklin Square",
    "auto charging system repair shop",
    "car alternator malfunction repair",
    "vehicle electrical maintenance",
    "auto battery replacement service",
    "battery charging issue fix",
    "alternator output voltage check",
    "starter motor noise fix",
    "car won’t start electrical fix",
    "auto repair shop Long Island",
    "vehicle battery installation expert",
    "affordable car battery replacement",
    "battery failure diagnosis",
    "car battery efficiency test",
    "auto repair Franklin Square NY",
    "battery cell test service",
    "auto electrical diagnostic center",
    "alternator system testing Long Island",
    "vehicle not starting diagnosis",
    "charging system voltage check",
    "battery power performance test",
    "battery and alternator health check",
    "automotive electrical service shop",
    "vehicle electrical repair Long Island",
    "auto power system troubleshooting",
    "battery replacement experts Franklin Square",
    "car won’t start no power fix",
    "auto diagnostic service Long Island",
    "best battery and charging service",
    "vehicle electrical system tune-up",
    "alternator replacement shop",
    "battery maintenance specialist",
    "trusted car battery service Long Island",
    "everything auto battery repair",
    "car battery experts Franklin Square",
    "Long Island auto electrical repair",
    "reliable vehicle battery diagnostics",
    "affordable car electrical repair"
  ],
  openGraph: {
    title: "Battery Services | Everything Auto - Franklin Square",
    description:
      "Professional car battery testing, replacement, and charging system diagnostics in Franklin Square & Long Island.",
    url: "https://everythingauto.com/battery-services",
    siteName: "Everything Auto",
    images: [
      {
        url: "https://images.unsplash.com/photo-1620027582885-78c6686a6352?w=1200&h=600&fit=crop",
        width: 1200,
        height: 600,
        alt: "Car Battery Replacement Service",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  metadataBase: new URL("https://everythingauto.com"),
};

export default async function Home() {
  return (
    <>
      <BatteryServices />
    </>
  );
}
