import ElectricalSystems from "./components/ElectricalSystems";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Expert Electrical System Repair in Franklin Square",
  description:
    "Professional electrical diagnostics and repair for vehicles in Franklin Square. We fix wiring, alternators, batteries, and starters to keep your car running smoothly.",
  keywords: [
    "auto electrical repair",
    "car electrical system service",
    "vehicle wiring repair",
    "battery replacement Franklin Square",
    "alternator repair Franklin Square",
    "starter repair Franklin Square",
    "automotive electrical diagnostics",
    "electrical system inspection",
    "car wiring troubleshooting",
    "power window repair",
    "car door lock repair",
    "auto alternator testing",
    "starter motor replacement",
    "car light repair",
    "headlight replacement Franklin Square",
    "taillight repair service",
    "electrical fault detection",
    "vehicle lighting system repair",
    "power accessory repair",
    "auto fuse replacement",
    "relay testing service",
    "ignition system repair",
    "charging system diagnostics",
    "electrical short detection",
    "automotive circuit testing",
    "vehicle ECU diagnostics",
    "engine electrical repair",
    "battery drain issue fix",
    "auto wiring harness repair",
    "alternator replacement service",
    "starter testing service",
    "car electrical troubleshooting",
    "auto electrician Franklin Square",
    "vehicle wiring diagnostics",
    "fuse box repair",
    "automotive lighting replacement",
    "electrical control system repair",
    "car power seat repair",
    "vehicle power locks repair",
    "car electrical issue repair",
    "battery voltage test",
    "alternator belt service",
    "starter relay inspection",
    "electrical load testing",
    "vehicle electronics repair",
    "dashboard light diagnostics",
    "car horn repair",
    "auto sensor replacement",
    "electrical maintenance service",
    "vehicle power distribution repair",
    "alternator failure fix",
    "starter solenoid replacement",
    "automotive electrical components",
    "engine electrical testing",
    "battery terminal cleaning",
    "ground wire repair",
    "car ECU electrical test",
    "auto power outlet repair",
    "vehicle wiring inspection",
    "charging system service",
    "electronic system repair",
    "vehicle voltage regulator repair",
    "auto electrician Long Island",
    "car electric repair near me",
    "vehicle electronics testing",
    "headlight circuit repair",
    "alternator diagnostic service",
    "starter system repair",
    "battery load test Franklin Square",
    "auto electrical replacement parts",
    "car signal light repair",
    "wiring harness replacement",
    "power window switch repair",
    "vehicle electrical safety inspection",
    "diagnostic electrical repair",
    "car charging system repair",
    "alternator bearing replacement",
    "electrical control unit service",
    "engine electrical fault detection",
    "auto electrical repair Long Island",
    "vehicle electrical expert Franklin Square",
    "battery charging diagnostics",
    "auto repair electrical specialist",
    "starter installation Franklin Square",
    "alternator inspection Franklin Square",
    "car electrical testing service",
    "automotive repair shop Franklin Square",
    "electrical diagnostics and testing",
    "power mirror repair",
    "auto electrical system maintenance",
    "wiring issue detection",
    "battery and alternator test",
    "vehicle electrical service Franklin Square",
    "car electronics repair shop",
    "professional electrical repair Long Island",
    "auto repair specialists Franklin Square",
    "electrical diagnostics near me",
    "automotive power system repair",
    "everything auto Franklin Square",
    "auto service electrical diagnostics"
  ],
};

export default async function Home() {
  return (
    <>
      <ElectricalSystems />
    </>
  );
}
