import NYStateInspection from "./components/NYStateInspection";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NY State Inspection in Franklin Square | Everything Auto",
  description:
    "Official New York State vehicle inspection station in Franklin Square. Everything Auto provides fast, certified safety and emissions inspections for all car makes and models in Nassau County.",
  keywords: [
    "NY state inspection Franklin Square",
    "New York vehicle inspection",
    "car inspection Franklin Square NY",
    "safety inspection near me",
    "emissions inspection Nassau County",
    "NYS inspection station",
    "inspection station Franklin Square",
    "NYS-certified inspection shop",
    "vehicle emissions testing",
    "car safety inspection Long Island",
    "annual car inspection NY",
    "New York inspection requirements",
    "official NYS inspection center",
    "car inspection service Franklin Square",
    "auto inspection near Garden City",
    "vehicle inspection Elmont",
    "inspection station near West Hempstead",
    "inspection shop Valley Stream",
    "New York State emissions test",
    "car check safety inspection",
    "NYS inspection for hybrid cars",
    "EV vehicle inspection NY",
    "commercial vehicle inspection Nassau County",
    "fast car inspection Franklin Square",
    "same-day NY inspection",
    "inspection without appointment NY",
    "walk-in inspection Franklin Square",
    "vehicle registration inspection NY",
    "safety inspection checklist NY",
    "emission test service Franklin Square",
    "NYS DMV certified inspection",
    "everything auto NY inspection",
    "inspection for used cars NY",
    "auto inspection near me",
    "inspection renewal New York",
    "safety and emissions testing Long Island",
    "inspection for gas cars NY",
    "inspection for electric cars NY",
    "NYS inspection sticker renewal",
    "inspection near Nassau County",
    "car inspection shop near me",
    "inspection for sedans SUVs trucks",
    "quick inspection Franklin Square",
    "auto emissions diagnostics NY",
    "tailpipe emissions test",
    "vehicle readiness inspection",
    "car check engine light inspection",
    "NYS inspection failed repair",
    "inspection repair service Franklin Square",
    "inspection failure recheck NY",
    "NYS inspection checklist",
    "auto emissions repair Franklin Square",
    "inspection renewal notice NY",
    "inspection deadline New York",
    "inspection expired car NY",
    "where to get NYS inspection",
    "licensed NY inspection garage",
    "trusted inspection station Nassau County",
    "DMV certified auto inspection",
    "affordable car inspection NY",
    "inspection location Franklin Square",
    "inspection shop near Hempstead",
    "inspection station near Mineola",
    "car inspection Valley Stream",
    "vehicle emissions test near me",
    "inspection for out-of-state cars",
    "inspection appointment NY",
    "inspection renewal Franklin Square",
    "NYS inspection due reminder",
    "inspection and repair same day",
    "inspection for luxury cars NY",
    "inspection for trucks NY",
    "inspection for fleet vehicles NY",
    "vehicle inspection shop Nassau County",
    "safety inspection car Long Island",
    "inspection for hybrid EV Franklin Square",
    "auto inspection pricing NY",
    "inspection near 11010 ZIP code",
    "inspection DMV approved station",
    "inspection walk-in Franklin Square NY",
    "fast emissions inspection Nassau County",
    "inspection certificate NY",
    "inspection appointment not required",
    "inspection sticker NY renewal",
    "trusted auto shop Franklin Square",
    "Everything Auto inspection",
    "inspection service Long Island NY",
    "safety and emissions experts NY",
    "inspection pass guarantee NY",
    "inspection with repair service NY",
    "inspection for all car makes",
    "car inspection time Franklin Square",
    "15 minute NY inspection",
    "auto inspection open Saturday NY",
    "inspection for commercial vehicles",
    "inspection near West Hempstead",
    "inspection for daily drivers NY",
    "official inspection Long Island",
    "NYS-certified car inspection Franklin Square",
    "inspection station trusted Franklin Square",
    "auto shop inspection services",
    "best NY inspection near me",
    "reliable car inspection Franklin Square"
  ],
};

export default async function Home() {
  return (
    <>
      <NYStateInspection />
    </>
  );
}
