import BrakeService from "./components/BrakeService";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Brake Service & Repair | Everything Auto Franklin Square NY",
  description:
    "Professional brake inspections, repairs, and replacements in Franklin Square, NY. Ensure safety with expert brake maintenance by Everything Auto – trusted Long Island mechanics.",
  keywords: [
    "brake service Franklin Square",
    "brake repair Long Island",
    "brake pad replacement Franklin Square",
    "rotor resurfacing Long Island",
    "brake inspection near me",
    "ABS diagnostics Franklin Square",
    "brake fluid flush service",
    "auto brake shop near me",
    "car brake repair Long Island",
    "emergency brake repair Franklin Square",
    "brake replacement service",
    "squeaky brakes fix",
    "spongy brake pedal repair",
    "brake caliper replacement",
    "brake line replacement",
    "anti-lock brake system service",
    "vehicle brake maintenance Long Island",
    "Everything Auto brake repair",
    "affordable brake repair Franklin Square",
    "certified brake technicians",
    "Long Island auto brake shop",
    "complete brake service NY",
    "car pulls when braking",
    "vibration when braking fix",
    "brake safety check Long Island",
    "trusted auto shop Franklin Square",
    "brake wear indicator check",
    "rotor replacement Franklin Square",
    "front and rear brake pads service",
    "car stopping distance issue",
    "hydraulic brake system service",
    "ABS light diagnostics",
    "auto mechanic Long Island NY",
    "brake system inspection NY",
    "local car brake shop",
    "everything auto services",
    "Franklin Square brake center",
    "Long Island automotive repair",
    "top brake repair shop NY",
    "best brake service Franklin Square",
    "brake pedal vibration fix",
    "squealing brake noise repair",
    "wheel cylinder repair service",
    "disc brake maintenance Long Island",
    "drum brake repair Franklin Square",
    "rotor warping fix",
    "auto fluid replacement service",
    "car brake leak repair",
    "hydraulic brake inspection",
    "brake booster testing",
    "ABS sensor replacement",
    "complete brake overhaul NY",
    "auto brake experts Franklin Square",
    "everything auto long island brakes",
    "quality car brake parts NY",
    "brake pad life extension tips",
    "auto brake maintenance schedule",
    "car brake repair coupons NY",
    "trusted mechanic Long Island NY",
    "vehicle safety inspection Franklin Square",
    "brake line leak detection",
    "ABS troubleshooting Long Island",
    "affordable brake pads NY",
    "Franklin Square brake shop",
    "Long Island NY brake repair shop",
    "car shaking while braking fix",
    "reliable auto repair Franklin Square",
    "wheel alignment and brake service",
    "car vibration issue fix",
    "auto repair and brake care NY",
    "professional car brake inspection",
    "automotive brake diagnostics NY",
    "Long Island NY brake center",
    "auto brake specialists Franklin Square",
    "quality brake system replacement",
    "auto brake test Long Island",
    "Long Island car service center",
    "local mechanic for brakes NY",
    "brake flush and service Franklin Square",
    "auto brake light issue fix",
    "Long Island NY auto experts",
    "Franklin Square auto center",
    "affordable vehicle brake service NY",
    "trusted brake maintenance shop",
    "Long Island car repair experts",
    "auto repair Long Island Franklin Square",
    "best car service NY brakes",
    "auto repair near Franklin Square",
    "brake fix Long Island mechanic",
    "vehicle brake repair near me",
    "trusted car maintenance shop NY",
    "auto care Long Island Franklin Square",
    "top-rated brake shop NY",
    "Long Island brake professionals",
    "auto workshop Franklin Square",
    "car brakes inspection and maintenance",
    "emergency brake service NY",
    "auto safety inspection Long Island",
    "Long Island vehicle service center",
    "car mechanics Franklin Square NY",
    "complete brake checkup NY",
    "Long Island NY car repair shop",
    "auto brake repair Franklin Square NY",
    "everything auto Long Island NY",
  ],
};

export default async function Home() {
  return (
    <>
      <BrakeService />
    </>
  );
}
