import type { Metadata } from "next";
import About from "./components/About";

export const metadata: Metadata = {
  title: "Everything Auto - Expert Auto Repair in Franklin Square, NY | About",
  description:
    "Discover Everything Auto — your trusted auto repair partner in Franklin Square, NY. Family-owned since 2008, providing honest, high-quality service and ASE-certified technicians you can rely on.",
  keywords: [
    "about Everything Auto",
    "auto repair history Franklin Square",
    "family-owned auto repair NY",
    "trusted car repair shop Long Island",
    "Everything Auto team",
    "ASE certified mechanics Franklin Square",
    "auto experts in Nassau County",
    "car maintenance professionals NY",
    "quality auto workmanship",
    "reliable car service Franklin Square",
    "experienced auto technicians",
    "auto repair legacy Long Island",
    "professional vehicle care NY",
    "Everything Auto experience",
    "customer-focused car repair shop",
    "honest auto mechanics Franklin Square",
    "top-rated auto shop NY",
    "auto diagnostics experts",
    "vehicle maintenance excellence",
    "auto service specialists Nassau County",
    "everything auto commitment",
    "trusted by Franklin Square drivers",
    "auto repair transparency",
    "vehicle safety inspection experts",
    "dedicated car service Long Island",
    "premium car care NY",
    "automotive service you can trust",
    "longstanding auto business NY",
    "award-winning auto service",
    "local auto repair specialists",
    "mechanic shop with values",
    "auto maintenance experts Franklin Square",
    "best car repair Franklin Square NY",
    "Everything Auto reviews",
    "car care reputation Long Island",
    "dependable car repair services",
    "auto workshop integrity",
    "affordable car service NY",
    "everything auto philosophy",
    "commitment to quality auto repair",
    "auto care excellence Franklin Square",
    "vehicle diagnostics experts",
    "Nassau County mechanic shop",
    "automotive service legacy",
    "community trusted car repair",
    "auto repair shop values",
    "Everything Auto mission",
    "experienced repair team NY",
    "customer satisfaction auto repair",
    "mechanic shop Franklin Square NY",
    "auto specialists you can rely on",
    "Long Island car experts",
    "friendly auto repair NY",
    "transparent pricing auto repair",
    "family business auto shop",
    "Everything Auto story",
    "Franklin Square car experts",
    "neighborhood auto service",
    "dedicated car repair Franklin Square",
    "auto care professionals NY",
    "local vehicle maintenance experts",
    "customer-first auto repair",
    "Everything Auto reliability",
    "precision auto repairs",
    "expert auto inspection NY",
    "top automotive service Long Island",
    "trusted NY auto shop",
    "high-quality car repair Franklin Square",
    "certified automotive technicians",
    "Everything Auto reputation NY",
    "Long Island vehicle maintenance",
    "auto excellence Franklin Square NY",
    "Everything Auto commitment NY",
    "trusted mechanics Long Island",
    "car service integrity",
    "top Franklin Square auto repair center",
    "everything auto dedication",
    "community-driven auto shop",
    "local car repair excellence",
    "trusted auto specialists NY",
    "affordable reliable auto care",
    "auto repair professionalism",
    "highly rated auto repair Nassau County",
    "Everything Auto ethics",
    "automotive experience NY",
    "skilled car technicians Franklin Square",
    "Everything Auto team story",
    "honest car care Long Island",
    "trusted mechanic experts",
    "auto repair craftsmanship",
    "best car maintenance Franklin Square",
    "everything auto values NY",
    "auto shop leadership",
    "Everything Auto Long Island NY",
    "automotive repair standards NY",
    "auto repair innovation",
    "Everything Auto customer service",
    "Franklin Square trusted mechanics",
    "Nassau County car shop",
    "Everything Auto family values",
    "top auto care Long Island NY",
    "professional car diagnostics",
    "Everything Auto trusted by locals",
    "certified auto repair Franklin Square",
    "vehicle repair experience NY"
  ],
};

export default function Home() {
  return (
    <>
      <About />
    </>
  );
}
