import { Metadata } from "next";
import WheelTire from "./components/WheelTire";

export const metadata : Metadata = {
  title: "Wheel & Tire Services | Tire Sales, Alignment & Repairs - Everything Auto Franklin Square NY",
  description:
    "Expert wheel and tire services at Everything Auto in Franklin Square, NY — including tire sales, installation, rotation, balancing, alignment, and puncture repair. Trusted auto experts near you.",
  keywords: [
    "wheel and tire services",
    "tire services franklin square",
    "everything auto tire shop",
    "tire installation franklin square",
    "tire rotation service",
    "wheel alignment franklin square",
    "tire balancing service",
    "flat tire repair",
    "puncture repair service",
    "car tire replacement",
    "wheel balancing service",
    "tire mounting service",
    "two-wheel alignment",
    "four-wheel alignment",
    "tire maintenance tips",
    "wheel repair near me",
    "tire shop long island",
    "everything auto wheels",
    "auto wheel service",
    "tire inspection",
    "wheel inspection service",
    "tire tread depth check",
    "wheel straightening",
    "wheel rim repair",
    "car wheel care",
    "everything auto tire experts",
    "tire pressure check",
    "tire pressure monitoring system service",
    "tpms sensor replacement",
    "run flat tires",
    "performance tires",
    "summer tires",
    "winter tires",
    "all season tires",
    "tire wear patterns",
    "vehicle vibration fix",
    "car pulls to one side",
    "steering vibration repair",
    "tire balancing experts",
    "wheel alignment precision",
    "road force balancing",
    "wheel hub repair",
    "everything auto franklin square",
    "new tires installation",
    "car tire brands",
    "michelin tires",
    "goodyear tires",
    "bridgestone tires",
    "continental tires",
    "pirelli tires",
    "cooper tires",
    "firestone tires",
    "yokohama tires",
    "hankook tires",
    "kumho tires",
    "wheel and rim services",
    "rim replacement franklin square",
    "tire shop new york",
    "auto tire repair shop",
    "vehicle wheel alignment ny",
    "everything auto wheel balancing",
    "wheel rotation specialists",
    "auto tire diagnostics",
    "everything auto tire alignment",
    "auto repair shop tires",
    "everything auto services",
    "flat tire patch service",
    "emergency tire service",
    "tire shop near me",
    "wheel repair shop",
    "mobile tire repair franklin square",
    "everything auto flat tire fix",
    "wheel bearing replacement",
    "tire blowout repair",
    "tire vibration check",
    "wheel rim polishing",
    "tire rotation frequency",
    "tire life extension",
    "everything auto tire care",
    "automotive wheel balancing",
    "car suspension alignment",
    "vehicle ride comfort",
    "tire wear troubleshooting",
    "wheel damage detection",
    "everything auto alignment center",
    "wheel balancing precision tools",
    "everything auto tire diagnostics",
    "tire leak check",
    "valve stem replacement",
    "tire mounting and balancing",
    "new tire discounts franklin square",
    "cheap tires long island",
    "affordable tire replacement",
    "premium tires ny",
    "high performance wheel balancing",
    "vehicle steering alignment",
    "wheel tracking adjustment",
    "precision tire balancing",
    "everything auto tire rotation service",
    "everything auto wheel center",
    "alignment specialist franklin square",
    "auto tire packages",
    "car rim services",
    "everything auto tire safety check",
    "tire puncture inspection",
    "flat tire diagnosis",
    "rim straightening service",
    "wheel vibration correction",
    "tire patch installation",
    "roadside tire repair",
    "automotive tire fitting",
    "car alignment ny",
    "wheel balancing experts franklin square",
    "everything auto tire pressure maintenance",
    "wheel maintenance routine",
    "everything auto tire checkup",
    "wheel rotation guide",
    "tire service packages",
    "wheel service center",
    "everything auto customer care",
    "vehicle tire diagnostics",
    "wheel rim upgrade",
    "everything auto rim replacement",
    "auto tire pressure issues",
    "vehicle handling improvement",
    "alignment repair ny",
    "everything auto wheel service",
    "everything auto tire experts ny",
    "wheel and tire combo packages",
    "auto wheel shop franklin square",
    "everything auto road safety",
    "new tire offers ny",
    "wheel torque inspection",
    "tire balancing procedure",
    "everything auto high speed balancing",
    "wheel adjustment process",
    "tire services nearby",
    "auto tire and wheel care",
    "wheel safety check",
    "tire puncture sealant",
    "everything auto flat tire repair",
    "tire service franklin square ny",
    "auto tire check franklin square",
    "wheel rotation service",
    "tire service near franklin square",
    "everything auto tire shop ny",
    "auto tire pressure sensor",
    "tire alignment service",
    "everything auto tire change",
    "auto wheel balancing",
    "tire installation center",
    "wheel tire maintenance ny",
    "tire tread inspection service",
    "everything auto wheel balancing ny",
    "vehicle tire safety check",
    "everything auto tire balancing experts",
    "wheel and tire inspection",
    "wheel alignment long island",
    "auto service franklin square ny",
    "everything auto tire repair long island",
    "tire inflation check",
    "everything auto car wheels",
    "wheel rotation near me",
    "wheel inspection near me",
    "everything auto tire adjustment",
    "vehicle vibration problem",
    "everything auto steering fix",
    "alignment shop near franklin square",
    "everything auto new tires",
    "everything auto used tires",
    "car wheel straightening ny",
    "auto tire care long island",
    "everything auto maintenance",
    "vehicle wheel diagnostics",
    "tire balancing machine",
    "car wheel hub issues",
    "everything auto quality tires",
    "flat tire repair ny",
    "everything auto alignment check",
    "tire rotation franklin square",
    "everything auto vehicle maintenance",
    "car wheel installation",
    "tire checkup franklin square",
    "auto tire puncture patch",
    "everything auto road safety tips",
    "wheel care solutions",
    "tire and rim combo installation",
    "everything auto expert mechanics",
    "wheel balance franklin square",
    "auto service alignment experts",
    "wheel damage repair ny",
    "car tire packages",
    "everything auto tire center",
    "tire store near me",
    "tire air pressure adjustment",
    "wheel mounting",
    "everything auto wheel balancing experts",
    "car handling improvement",
    "wheel bearing service ny",
    "tire repair shop near me",
    "auto wheel adjustment",
    "wheel rim checkup",
    "everything auto tire maintenance center",
    "wheel balance ny",
    "everything auto precision alignment",
    "auto wheel specialist",
    "wheel alignment correction",
    "everything auto rim care",
    "tire puncture fix ny",
    "everything auto tire rotation frequency",
    "wheel rim replacement ny",
    "everything auto wheel safety",
    "auto tire brands comparison",
    "tire grip testing",
    "everything auto tire tread check",
    "wheel repair technicians",
    "everything auto best tire brands",
    "auto wheel alignment adjustment",
    "everything auto tire installation process",
    "vehicle tire management",
    "everything auto wheel alignment test",
    "tire repair and rotation combo",
    "everything auto high quality service",
    "auto wheel diagnostics ny",
    "everything auto smooth ride",
    "vehicle wheel health",
    "everything auto service excellence",
    "auto tire leak fix",
    "everything auto car tire service",
    "auto wheel balancing long island",
    "tire and wheel service deals",
    "everything auto certified alignment",
    "wheel tread wear issues",
    "everything auto tire performance",
    "everything auto wheel rotation plan",
    "tire replacement experts",
    "everything auto rim protection",
    "vehicle tire inspection service",
    "wheel maintenance tips",
    "everything auto auto tire rotation",
    "auto wheel and rim service ny",
    "tire tread measurement",
    "wheel tracking alignment",
    "everything auto reliable service",
    "tire mounting experts",
    "everything auto rim inspection",
    "everything auto customer satisfaction",
    "tire balancing service ny",
    "everything auto auto wheel check",
    "everything auto professional tire care",
    "car wheel repair specialists",
    "everything auto accurate balancing",
    "wheel tire setup experts",
    "everything auto tire center long island",
    "vehicle ride improvement",
    "auto wheel balancing accuracy",
    "everything auto local tire shop",
    "tire balancing nyc",
    "everything auto tire deals",
    "wheel installation specialists",
    "everything auto wheel center franklin square",
    "auto wheel balance setup",
    "everything auto best tire deals",
    "auto repair tire rotation",
    "everything auto tire and wheel service",
    "auto tire installation near me",
    "everything auto reliable tire repair",
    "everything auto professional alignment",
    "wheel care and safety",
    "everything auto wheel check",
    "wheel balancing accuracy test",
    "everything auto precision service",
    "tire and wheel combination setup",
    "everything auto service center franklin square",
    "everything auto tire alignment services",
    "car tire wheel setup",
    "everything auto full tire service",
    "auto wheel and tire adjustment",
    "everything auto high end tire care",
    "everything auto tire performance tuning",
    "everything auto road alignment",
    "tire wear correction",
    "everything auto tire service ny",
    "everything auto wheel rotation ny",
    "everything auto affordable tires",
    "wheel balancing precision service",
    "everything auto wheel and tire maintenance",
    "everything auto expert alignment services",
    "car tire services franklin square",
    "everything auto tire life extension",
    "tire checkup and repair",
    "everything auto wheel tire packages",
    "auto repair shop wheel services",
    "everything auto balance correction",
    "wheel rim damage fix",
    "everything auto rim diagnostics",
    "everything auto tire maintenance tips",
    "everything auto perfect alignment",
    "auto wheel specialists ny",
    "everything auto alignment shop ny",
    "everything auto auto care professionals",
    "vehicle wheel repair experts",
    "everything auto tire savings",
    "everything auto tire expert service",
    "everything auto wheel performance",
    "auto tire replacement long island",
    "everything auto tire and rim inspection",
    "everything auto perfect tire fit",
    "everything auto tire care solutions",
    "auto wheel integrity check",
    "everything auto tire balance service",
    "everything auto top quality wheels",
    "auto wheel upgrade ny",
    "everything auto safe driving",
    "wheel and tire professional service",
    "everything auto car safety inspection",
    "auto tire balancing near me",
    "everything auto wheel tracking test",
    "everything auto safety alignment",
    "auto tire tread wear fix",
    "everything auto trusted wheel care",
    "vehicle tire balancing and repair",
    "everything auto best alignment center"
  ],
};

export default async function Home() {
  return (
    <>
      <WheelTire />
    </>
  );
}
