import CarCarePlans from "./components/CarCarePlans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Car Care Plans | Everything Auto - Maintenance & Protection Packages",
  description:
    "Explore Everything Auto's Car Care Plans — tailored maintenance and protection packages to keep your vehicle performing at its best. Affordable, reliable, and trusted in Franklin Square and Long Island.",
  keywords: [
    "Car care plans",
    "Auto maintenance packages",
    "Vehicle protection plans",
    "Long Island car service plans",
    "Everything Auto maintenance",
    "Affordable car care",
    "Comprehensive auto service",
    "Vehicle maintenance Franklin Square",
    "Auto repair membership",
    "Car service deals",
    "Car protection package",
    "Preventive car maintenance",
    "Best car service Long Island",
    "Regular car maintenance plan",
    "Auto service Franklin Square NY",
    "Car tune-up plan",
    "Oil change packages",
    "Brake maintenance plan",
    "Tire rotation service plan",
    "Fleet maintenance programs",
    "Car inspection plan",
    "Engine protection plan",
    "Car diagnostic service",
    "Auto repair coverage",
    "Monthly car maintenance plan",
    "Annual car service plan",
    "Long Island vehicle care",
    "Auto detailing plan",
    "Battery maintenance plan",
    "Roadside assistance plan",
    "Auto performance plan",
    "Trusted car mechanics",
    "Long-term car protection",
    "Professional car maintenance",
    "Auto service subscription",
    "Vehicle warranty extension",
    "Routine car checkup plan",
    "Car servicing membership",
    "Scheduled auto maintenance",
    "Tire and wheel protection",
    "Engine care package",
    "Transmission maintenance plan",
    "Air conditioning service plan",
    "Car health check program",
    "Multi-point inspection plan",
    "Car fluid check plan",
    "Electrical system maintenance",
    "Long Island auto experts",
    "Franklin Square car care",
    "Best mechanic near me",
    "Local auto repair plan",
    "Premium car maintenance package",
    "Eco-friendly car service",
    "Hybrid vehicle maintenance",
    "Luxury car service plan",
    "SUV maintenance plan",
    "Truck care package",
    "Regular oil and filter change",
    "Brake inspection plan",
    "Cooling system maintenance",
    "Suspension check plan",
    "Auto service near me",
    "Long Island vehicle upkeep",
    "Trusted auto professionals",
    "Complete car care program",
    "Car care discounts",
    "Auto repair savings plan",
    "Family car maintenance plan",
    "Student car service plan",
    "Professional auto packages",
    "Affordable vehicle upkeep",
    "Reliable car repair program",
    "New York auto service",
    "Vehicle service bundles",
    "All-in-one car care plan",
    "Trusted Long Island auto shop",
    "Franklin Square car experts",
    "Best vehicle protection plans",
    "Oil and filter maintenance",
    "Vehicle fluid replacement plan",
    "Premium service membership",
    "Car warranty plan",
    "Long Island preventive maintenance",
    "Extended vehicle coverage",
    "Car tune-up package",
    "Full-service car plan",
    "Top-rated auto care NY",
    "Road trip vehicle service plan",
    "Safe driving maintenance plan",
    "Car longevity package",
    "Professional auto diagnostics",
    "Engine health plan",
    "Maintenance for used cars",
    "Maintenance for new cars",
    "Year-round vehicle care",
    "Trusted automotive technicians",
    "Performance maintenance plan",
    "Long-lasting vehicle plan",
    "Comprehensive car protection",
    "Regular vehicle inspections",
    "Everything Auto plans",
    "Long Island car maintenance",
    "Franklin Square auto service plans"
  ],
  metadataBase: new URL("https://everythingauto.com"),
};

export default async function Home() {
  return (
    <>
      <CarCarePlans />
    </>
  );
}
