// import Blog from "./components/Blog";
import Contact from "./components/Contact";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Everything Auto | Franklin Square Auto Repair & Service Experts",
  description:
    "Contact Everything Auto in Franklin Square, NY for trusted car repair, diagnostics, and maintenance services. Call (516) 775-9724 or visit 980 Washington St for expert automotive care.",
  keywords: [
    "Contact Everything Auto",
    "Everything Auto contact",
    "Auto repair Franklin Square contact",
    "Car service contact Long Island",
    "Franklin Square auto shop phone",
    "Auto repair appointment NY",
    "Everything Auto directions",
    "Auto repair shop address Franklin Square",
    "Call Everything Auto",
    "Everything Auto phone number",
    "Auto repair customer service",
    "Car repair inquiry Long Island",
    "Book auto service Franklin Square",
    "Email Everything Auto",
    "Auto repair estimate Franklin Square",
    "Everything Auto consultation",
    "Vehicle maintenance quote",
    "Contact local mechanic Franklin Square",
    "Auto diagnostic booking",
    "Car inspection appointment",
    "Brake service appointment",
    "Engine repair contact",
    "Transmission repair contact",
    "NY State Inspection contact",
    "Car repair near Garden City contact",
    "Auto repair near Hempstead contact",
    "Auto service hours Franklin Square",
    "Auto repair open today Franklin Square",
    "Everything Auto business hours",
    "Trusted car mechanics contact",
    "Auto service Franklin Square NY",
    "Long Island auto care contact",
    "Vehicle repair consultation",
    "Schedule auto repair NY",
    "Book oil change Franklin Square",
    "Car repair form submission",
    "Auto service message form",
    "Car repair request online",
    "Automotive repair customer support",
    "Auto repair help desk",
    "Franklin Square auto experts",
    "Everything Auto free quote",
    "Automotive support Franklin Square",
    "Auto maintenance appointment",
    "Trusted auto technicians NY",
    "Vehicle service inquiry Long Island",
    "Car battery replacement contact",
    "Brake repair contact Franklin Square",
    "Auto electrical repair contact",
    "NY vehicle service form",
    "Engine diagnostics contact",
    "Oil change contact Everything Auto",
    "Transmission expert Franklin Square",
    "Car AC repair contact",
    "Everything Auto near me",
    "Local auto shop contact",
    "Auto repair map location",
    "980 Washington St Franklin Square",
    "Everything Auto directions map",
    "Call for car repair Franklin Square",
    "Auto service hotline",
    "Everything Auto reviews contact",
    "Trusted car care Franklin Square",
    "Auto repair quote Long Island",
    "Car shop contact Nassau County",
    "Automotive help Franklin Square",
    "Everything Auto Franklin Square NY",
    "Vehicle maintenance contact form",
    "Auto care schedule service",
    "Car shop opening hours",
    "Customer inquiry car repair",
    "Franklin Square auto shop inquiry",
    "Vehicle repair near me",
    "Mechanic booking Franklin Square",
    "Long Island automotive service contact",
    "Top rated auto repair Franklin Square",
    "Best car shop contact Long Island",
    "Affordable auto repair contact",
    "Professional mechanics contact",
    "Everything Auto service inquiry",
    "Vehicle diagnostic booking NY",
    "Car shop email Franklin Square",
    "Car repair call today",
    "Auto maintenance schedule call",
    "Emergency car repair contact",
    "Auto body service contact",
    "Car inspection schedule",
    "Everything Auto NY contact form",
    "Schedule brake repair",
    "Auto shop contact page",
    "Car repair booking NY",
    "Auto repair support Long Island",
    "Mechanic call assistance",
    "Schedule maintenance Franklin Square",
    "Everything Auto customer contact",
    "Automotive helpdesk NY",
    "Trusted mechanic Franklin Square NY",
    "Local auto care number",
    "Nassau County mechanic contact",
    "Vehicle service Franklin Square contact",
    "Everything Auto message form",
    "Book auto checkup Franklin Square",
    "Car care consultation Long Island",
    "Everything Auto repair assistance"
  ],
  metadataBase: new URL("https://everythingauto.com"),
};

export default async function Home() {
  return (
    <>
      <Contact />
    </>
  );
}
