import { Metadata } from "next";
import OilChanges from "./components/OilChanges";

export const metadata: Metadata = {
  title: "Oil Change Service in Franklin Square, NY | Everything Auto",
  description:
    "Get fast, professional, and affordable oil change services in Franklin Square, NY. We use premium synthetic and conventional oils to keep your engine healthy.",
  keywords: [
    "oil change Franklin Square NY",
    "synthetic oil change",
    "cheap oil change near me",
    "engine oil service",
    "oil filter replacement",
    "auto repair Franklin Square",
    "car maintenance Franklin Square",
    "Everything Auto oil change",
    "quick lube service",
    "affordable oil change",
    "vehicle maintenance service",
    "oil change special",
    "full synthetic oil change",
    "conventional oil change",
    "semi-synthetic oil change",
    "oil change deals",
    "engine lubrication service",
    "auto service Nassau County",
    "top rated oil change shop",
    "oil and filter change near me",
    "same day oil change",
    "best oil change shop Franklin Square",
    "local oil change service",
    "fast oil change Franklin Square",
    "professional oil change",
    "oil change coupons",
    "auto care Franklin Square",
    "vehicle inspection and oil change",
    "Nassau County oil change",
    "long island oil change shop",
    "quick oil change Long Island",
    "oil change near Hempstead",
    "oil change near Elmont",
    "oil change near Garden City",
    "oil change near West Hempstead",
    "oil change near Valley Stream",
    "oil change near Mineola",
    "auto shop Franklin Square NY",
    "engine care Franklin Square",
    "engine oil change Nassau County",
    "oil change without appointment",
    "walk-in oil change",
    "express oil service",
    "oil top-up service",
    "lubrication service Franklin Square",
    "oil change and maintenance",
    "complete car service",
    "engine protection service",
    "routine vehicle maintenance",
    "auto care center near me",
    "oil replacement",
    "oil service experts",
    "trusted oil change center",
    "oil flush service",
    "oil leak repair Franklin Square",
    "synthetic blend oil change",
    "high mileage oil change",
    "eco-friendly oil disposal",
    "digital vehicle inspection Franklin Square",
    "oil change appointment Franklin Square",
    "car repair and oil change",
    "certified oil change technicians",
    "best auto service shop Franklin Square",
    "oil service for SUVs",
    "oil service for trucks",
    "oil service for electric cars",
    "oil change pickup service",
    "Nassau County auto experts",
    "car repair and maintenance near me",
    "oil light reset service",
    "oil level check service",
    "premium oil service",
    "engine cleaning and oil change",
    "fast car maintenance Franklin Square",
    "oil change shop near me open now",
    "trusted local mechanics Franklin Square",
    "best-rated oil service Long Island",
    "affordable car care services",
    "oil change inspection checklist",
    "engine tune-up and oil service",
    "auto care family business Franklin Square",
    "oil change customer reviews",
    "NYS vehicle maintenance",
    "oil change long island ny",
    "oil change for hybrid cars",
    "eco synthetic oil service",
    "brake and oil service combo",
    "professional car oil service",
    "auto service center Franklin Square",
    "best oil change prices",
    "vehicle service near me",
    "Franklin Square auto care center",
    "maintenance shop near me",
    "auto service experts Franklin Square",
    "top auto repair Nassau County",
    "Everything Auto Franklin Square",
    "trusted car care shop",
    "oil change with digital inspection",
    "oil change trusted by locals",
    "quick vehicle maintenance Franklin Square",
    "oil change and filter replacement service",
    "car oil and fluid service",
    "auto maintenance Franklin Square NY",
    "car oil life service",
    "premium oil brands used",
    "high-performance oil change",
    "affordable and fast auto service",
    "local car service Franklin Square",
    "oil service and safety check",
    "fast auto maintenance near me",
    "oil change Franklin Square open today"
  ],
  openGraph: {
    title: "Oil Change Service in Franklin Square, NY | Everything Auto",
    description:
      "Fast, affordable, and professional oil change services for all makes and models in Franklin Square, NY. Visit Everything Auto today for quick and reliable service.",
    url: "https://everythingauto.com/oil-change",
    siteName: "Everything Auto",
    images: [
      {
        url: "https://images.unsplash.com/photo-1606214959239-181a4473c544?w=1200&h=600&fit=crop",
        width: 1200,
        height: 600,
        alt: "Oil Change Service Franklin Square NY",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default async function Home() {
  return (
    <>
      <OilChanges />
    </>
  );
}
