import Diagnostics from "./components/Diagnostics";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Professional Auto Diagnostics in Franklin Square",
  description:
    "Get precise vehicle diagnostics in Franklin Square. Our expert technicians use advanced tools to identify and repair check engine light issues, electrical faults, and performance problems.",
  keywords: [
    "auto diagnostics",
    "vehicle diagnostics",
    "check engine light service",
    "car diagnostic test",
    "engine diagnostics Franklin Square",
    "OBD-II scanning service",
    "auto repair diagnostics",
    "electrical system testing",
    "engine performance check",
    "diagnostic trouble codes",
    "car computer scan",
    "mechanic diagnostic service",
    "engine light diagnostics",
    "auto diagnostic center",
    "car fault detection",
    "professional auto service",
    "vehicle performance analysis",
    "check engine light Franklin Square",
    "diagnostic repair Franklin Square",
    "Nassau County car diagnostics",
    "full system diagnostics",
    "engine misfire diagnosis",
    "sensor testing service",
    "fuel system diagnostics",
    "battery and alternator testing",
    "engine checkup Franklin Square",
    "vehicle scanner service",
    "electronic diagnostics",
    "car diagnostic inspection",
    "automotive code reading",
    "advanced auto diagnostics",
    "vehicle data analysis",
    "auto repair troubleshooting",
    "OBD scan Franklin Square",
    "auto electrical diagnostics",
    "engine analysis service",
    "professional mechanic Franklin Square",
    "car computer diagnostics",
    "auto problem detection",
    "diagnostic scan service",
    "engine health inspection",
    "car troubleshooting Franklin Square",
    "vehicle system test",
    "engine light testing",
    "expert car diagnostics",
    "transmission diagnostics",
    "cooling system analysis",
    "auto check-up service",
    "car diagnostic repair shop",
    "automotive electrical test",
    "car sensor diagnostics",
    "advanced diagnostic tools",
    "diagnostic testing center",
    "auto issue detection",
    "ignition system diagnostics",
    "engine performance test",
    "air-fuel ratio diagnostics",
    "fuel injector testing",
    "engine power analysis",
    "emission system diagnostics",
    "exhaust diagnostics",
    "professional diagnostics Franklin Square",
    "vehicle repair diagnosis",
    "engine error code reading",
    "mechanical system testing",
    "electronic control unit scan",
    "car diagnostics Long Island",
    "auto scan Franklin Square",
    "vehicle maintenance diagnostics",
    "brake system diagnostics",
    "coolant temperature diagnostics",
    "transmission system check",
    "automotive fault scan",
    "engine RPM diagnostics",
    "car inspection Franklin Square",
    "complete vehicle diagnostics",
    "engine stalling diagnostics",
    "vehicle error detection",
    "auto electrical fault test",
    "car diagnostic center Franklin Square",
    "engine temperature diagnostics",
    "engine light repair Franklin Square",
    "car diagnostics expert",
    "mechanic diagnostic analysis",
    "car health check Franklin Square",
    "professional diagnostic report",
    "diagnostic service Long Island",
    "auto workshop Franklin Square",
    "car ECU diagnostics",
    "car repair diagnostics near me",
    "auto repair Franklin Square",
    "diagnostic service for vehicles",
    "engine analysis report",
    "auto maintenance Franklin Square",
    "OBD-II diagnostics Franklin Square",
    "comprehensive car diagnostics",
    "advanced diagnostic repair",
    "vehicle check engine analysis",
    "engine diagnostics near me",
    "everything auto diagnostics",
    "Franklin Square diagnostic experts"
  ],
};

export default async function Home() {
  return (
    <>
      <Diagnostics />
    </>
  );
}
