import AirConditioning from "./components/AirConditioning";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Air Conditioning Service | Everything Auto - Franklin Square",
  description:
    "Stay cool with our professional car air conditioning repair, recharge, and leak detection services in Franklin Square and Long Island. Expert auto A/C service you can trust.",
  keywords: [
    "car air conditioning repair",
    "auto AC service",
    "car AC recharge",
    "vehicle AC leak detection",
    "car AC compressor replacement",
    "car air conditioning maintenance",
    "automotive AC repair near me",
    "air conditioning service Franklin Square",
    "Long Island car AC repair",
    "vehicle cooling system service",
    "auto air conditioning specialist",
    "car AC not cooling fix",
    "car AC inspection",
    "refrigerant recharge service",
    "R134a recharge Long Island",
    "car AC freon refill",
    "AC leak test for cars",
    "vehicle AC pressure test",
    "AC vent temperature test",
    "air conditioner compressor repair",
    "car AC condenser replacement",
    "car AC evaporator cleaning",
    "auto climate control repair",
    "air conditioning system check",
    "car AC repair shop Long Island",
    "best auto AC service",
    "car AC system recharge",
    "fix my car AC",
    "auto air conditioning technician",
    "vehicle AC recharging near me",
    "automotive cooling expert",
    "car AC smell repair",
    "AC system maintenance car",
    "auto repair shop Franklin Square",
    "vehicle AC filter replacement",
    "auto AC system flushing",
    "fix AC compressor noise",
    "AC system tune-up",
    "AC diagnostic service",
    "car AC electrical issue repair",
    "vehicle AC hose replacement",
    "car air conditioning recharge service",
    "auto repair cooling system",
    "car cooling performance test",
    "AC system leak repair",
    "auto AC performance check",
    "AC vent airflow repair",
    "fix weak car AC",
    "AC system refrigerant top-up",
    "air conditioning system troubleshooting",
    "car AC refrigerant leak fix",
    "vehicle AC temperature sensor repair",
    "air conditioning belt replacement",
    "auto AC clutch repair",
    "car cabin cooling problem",
    "air conditioning system efficiency check",
    "car air conditioning recharge near me",
    "vehicle cooling diagnostics",
    "fix warm air from car AC",
    "auto AC refrigerant replacement",
    "AC compressor clutch replacement",
    "car cooling system pressure test",
    "auto AC leak detection Long Island",
    "car AC refrigerant leak detection",
    "auto AC filter cleaning",
    "car AC gas refill Franklin Square",
    "automotive AC repair shop",
    "best AC repair Long Island",
    "AC system maintenance Franklin Square",
    "vehicle air conditioning inspection",
    "car AC recharge deals",
    "auto air conditioning shop near me",
    "AC system diagnosis Long Island",
    "auto repair air conditioning",
    "AC system repair and service",
    "vehicle AC compressor fix",
    "car air conditioning system flush",
    "AC cooling test Long Island",
    "auto service air conditioning repair",
    "car climate control not working",
    "auto repair Franklin Square NY",
    "vehicle AC check-up service",
    "car AC replacement parts",
    "auto mechanic AC specialist",
    "best vehicle cooling service",
    "car AC performance check Long Island",
    "AC refrigerant replacement Long Island",
    "auto AC testing and repair",
    "vehicle cooling air conditioning fix",
    "auto air conditioning recharge Franklin Square",
    "car AC temperature issue fix",
    "auto air conditioning cleaning service",
    "vehicle AC system restoration",
    "car AC cooling fix Long Island",
    "everything auto AC service",
    "Long Island auto air conditioning expert",
    "Franklin Square AC car service",
    "affordable car AC repair",
    "trusted auto cooling repair Long Island"
  ],
  openGraph: {
    title: "Air Conditioning Service | Everything Auto - Franklin Square",
    description:
      "Professional car air conditioning repair, recharge, and leak detection in Franklin Square & Long Island.",
    url: "https://everythingauto.com/air-conditioning",
    siteName: "Everything Auto",
    images: [
      {
        url: "https://images.unsplash.com/photo-1605301149635-f938a9d1e4e0?w=1200&h=600&fit=crop",
        width: 1200,
        height: 600,
        alt: "Car Air Conditioning Service",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  metadataBase: new URL("https://everythingauto.com"),
};

export default async function Home() {
    return (
        <>
          <AirConditioning/>
        </>
    );
}
