import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientLayout from "./ClientLayout";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  metadataBase: new URL("https://everythingauto.com"),

  title: "Everything Auto - Expert Auto Repair in Franklin Square, NY",
  description:
    "Trusted auto repair shop in Franklin Square, NY. Family-owned since 2008. We provide oil changes, brake repair, diagnostics, inspections, and complete vehicle maintenance for all makes and models.",

  icons: {
    icon: [
      { url: "/favicon.svg", sizes: "16x16", type: "image/png" },
      { url: "/favicon.svg", sizes: "32x32", type: "image/png" },
      { url: "/favicon.svg", sizes: "192x192", type: "image/png" },
      { url: "/favicon.svg", sizes: "512x512", type: "image/png" },
    ],
    apple: "/favicon.svg",
    shortcut: "/favicon.svg",
  },
  keywords: [
    // Core Business Keywords
    "auto repair Franklin Square NY",
    "car mechanic Franklin Square",
    "auto service Franklin Square",
    "Everything Auto Franklin Square",
    "best auto repair near me",
    "auto repair shop Franklin Square",
    "car repair NY",
    "oil change Franklin Square",
    "brake repair Franklin Square",
    "engine diagnostics NY",
    "vehicle inspection Franklin Square",
    "auto tune up Franklin Square",
    "check engine light Franklin Square",
    "transmission repair Franklin Square",
    "battery replacement Franklin Square",
    "engine repair Franklin Square",
    "suspension repair Franklin Square",
    "steering repair Franklin Square",
    "exhaust system repair Franklin Square",
    "radiator repair Franklin Square",
    "AC repair Franklin Square NY",
    "wheel alignment Franklin Square",
    "tire rotation Franklin Square",
    "auto maintenance Franklin Square",
    "auto air conditioning repair NY",
    "car cooling system repair NY",

    // Extended Local SEO Keywords
    "auto repair Hempstead NY",
    "auto repair Elmont NY",
    "auto repair Garden City NY",
    "auto repair Valley Stream NY",
    "auto repair Floral Park NY",
    "auto repair Bellerose NY",
    "auto repair West Hempstead NY",
    "auto repair New Hyde Park NY",
    "auto repair Lynbrook NY",
    "auto repair Malverne NY",
    "auto repair Rockville Centre NY",
    "auto repair Stewart Manor NY",
    "auto repair Long Island NY",
    "auto repair Queens NY",
    "auto repair Brooklyn NY",
    "auto repair Bronx NY",
    "auto repair Manhattan NY",
    "auto repair Staten Island NY",
    "auto repair Nassau County NY",
    "auto repair Suffolk County NY",
    "auto repair NYC",
    "auto repair New York State",
    "auto repair New Jersey",
    "auto repair Connecticut",
    "auto repair Pennsylvania",

    // Oil Change Services
    "oil change near Franklin Square",
    "synthetic oil change Franklin Square",
    "cheap oil change Franklin Square",
    "full synthetic oil change NY",
    "conventional oil change Long Island",
    "quick lube Franklin Square",
    "oil and filter replacement NY",
    "engine oil flush Franklin Square",
    "oil service appointment Franklin Square",

    // Brakes
    "brake pad replacement Franklin Square",
    "brake rotor resurfacing NY",
    "ABS repair Franklin Square NY",
    "brake inspection Franklin Square",
    "brake fluid flush Franklin Square",
    "affordable brake repair Franklin Square",
    "emergency brake service Franklin Square",

    // Diagnostics
    "car diagnostics Franklin Square",
    "engine light diagnostics Franklin Square",
    "auto scan tool service NY",
    "engine check light repair NY",
    "OBD2 diagnostics Franklin Square",
    "auto electrical diagnostics NY",
    "engine performance check NY",

    // Engine Repair
    "engine rebuild Franklin Square",
    "engine replacement Franklin Square",
    "engine knocking repair Franklin Square",
    "engine oil leak repair Franklin Square",
    "timing belt replacement Franklin Square",
    "valve cover gasket repair NY",
    "spark plug replacement Franklin Square",
    "engine misfire repair Franklin Square",

    // Transmission
    "transmission rebuild Franklin Square",
    "transmission flush Franklin Square",
    "clutch repair Franklin Square NY",
    "automatic transmission service Franklin Square",
    "manual transmission service Franklin Square",
    "gear shifting issues repair Franklin Square",
    "transmission leak repair NY",

    // Suspension & Steering
    "shock absorber replacement Franklin Square",
    "strut replacement Franklin Square",
    "ball joint replacement Franklin Square",
    "tie rod replacement Franklin Square",
    "wheel alignment Franklin Square",
    "power steering repair Franklin Square",
    "suspension noise repair Franklin Square",
    "suspension inspection Franklin Square",

    // Wheel & Tire Services
    "tire shop Franklin Square NY",
    "new tires Franklin Square",
    "tire mounting Franklin Square",
    "tire balancing Franklin Square",
    "flat tire repair Franklin Square",
    "winter tires Franklin Square",
    "wheel alignment Franklin Square",
    "rim repair Franklin Square",
    "tire rotation Franklin Square",
    "run-flat tire service Franklin Square",

    // Preventative Maintenance
    "preventative maintenance Franklin Square",
    "vehicle tune up Franklin Square",
    "coolant flush Franklin Square",
    "power steering fluid change Franklin Square",
    "transmission fluid change Franklin Square",
    "engine air filter replacement Franklin Square",
    "cabin filter replacement Franklin Square",
    "fuel filter replacement Franklin Square",
    "spark plug service Franklin Square",

    // Electrical
    "starter replacement Franklin Square",
    "alternator repair Franklin Square",
    "battery testing Franklin Square",
    "electrical system diagnostics Franklin Square",
    "fuse box repair Franklin Square",
    "car wiring repair Franklin Square",
    "lighting repair Franklin Square NY",

    // Heating & Cooling
    "auto AC recharge Franklin Square",
    "auto heating repair Franklin Square",
    "car AC compressor replacement NY",
    "blower motor repair Franklin Square",
    "heater core repair Franklin Square",
    "radiator flush Franklin Square",
    "coolant system service Franklin Square",

    // Inspection & State Requirements
    "NY state inspection Franklin Square",
    "vehicle safety inspection Franklin Square",
    "emissions testing Franklin Square",
    "inspection station Franklin Square NY",
    "DOT inspection Franklin Square",
    "state certified mechanic Franklin Square",

    // Auto Body & Collision
    "auto body repair Franklin Square",
    "collision repair Franklin Square",
    "scratch and dent repair Franklin Square",
    "paint and refinishing Franklin Square",
    "frame alignment Franklin Square",
    "bumper repair Franklin Square NY",

    // Fleet Services
    "fleet maintenance Franklin Square",
    "commercial vehicle repair Franklin Square",
    "truck repair Franklin Square",
    "van repair Franklin Square",
    "corporate fleet auto service NY",

    // Seasonal & Specialized
    "winter car maintenance Franklin Square",
    "summer car maintenance Franklin Square",
    "road trip vehicle inspection Franklin Square",
    "seasonal tire change Franklin Square",

    // Customer Experience
    "affordable auto repair Franklin Square",
    "trusted mechanic Franklin Square",
    "family-owned auto shop Franklin Square",
    "certified auto technician Franklin Square",
    "same day auto repair Franklin Square",
    "emergency car repair Franklin Square",
    "Everything Auto reviews Franklin Square",
    "Everything Auto phone number",
    "Everything Auto directions",
    "Everything Auto opening hours",
    "Everything Auto services list",
    "Everything Auto near me",
    "Everything Auto NY contact",

    // Service Areas Expansion
    "auto repair Nassau County NY",
    "auto repair Suffolk County NY",
    "auto repair Queens County NY",
    "auto repair Brooklyn County NY",
    "auto repair Bronx County NY",
    "auto repair Manhattan County NY",
    "auto repair Long Island City NY",
    "auto repair Mineola NY",
    "auto repair Uniondale NY",
    "auto repair Freeport NY",
    "auto repair East Meadow NY",
    "auto repair Levittown NY",
    "auto repair Westbury NY",
    "auto repair Oceanside NY",
    "auto repair Bellmore NY",
    "auto repair Seaford NY",
    "auto repair Hicksville NY",
    "auto repair Farmingdale NY",
    "auto repair Great Neck NY",
    "auto repair Glen Cove NY",
    "auto repair Plainview NY",
    "auto repair Syosset NY",
    "auto repair North Bellmore NY",
    "auto repair Massapequa NY",
    "auto repair Rockville Centre NY",
    "auto repair Baldwin NY",
    "auto repair Merrick NY",
    "auto repair Roslyn NY",
    "auto repair Old Westbury NY",
    "auto repair Port Washington NY",
    "auto repair Huntington NY",
    "auto repair Commack NY",
    "auto repair Smithtown NY",
    "auto repair Brentwood NY",
    "auto repair Central Islip NY",
    "auto repair Babylon NY",
    "auto repair Bay Shore NY",
    "auto repair Patchogue NY",
    "auto repair Holbrook NY",
    "auto repair Ronkonkoma NY",
    "auto repair Sayville NY",
    "auto repair Montauk NY",

    // Marketing Keywords
    "top rated auto repair Franklin Square",
    "trusted car repair shop Franklin Square",
    "best mechanic shop Franklin Square",
    "local auto service Franklin Square",
    "affordable oil change NY",
    "expert transmission repair NY",
    "professional brake service Franklin Square",
    "trusted car diagnostics Franklin Square",
    "vehicle inspection experts Franklin Square",
    "Everything Auto New York",
    "Everything Auto Franklin Square NY auto service",
    "car mechanic Long Island NY",
    "auto service near me NY",
    "vehicle repair specialists Franklin Square",
    "Everything Auto car repair experts",
    // Additional 500 Keywords
    "Toyota repair Franklin Square NY",
    "Honda repair Franklin Square NY",
    "Ford repair Franklin Square NY",
    "Chevrolet repair Franklin Square NY",
    "Nissan repair Franklin Square NY",
    "BMW repair Franklin Square NY",
    "Mercedes repair Franklin Square NY",
    "Audi repair Franklin Square NY",
    "Volkswagen repair Franklin Square NY",
    "Tesla repair Franklin Square NY",
    "Lexus repair Franklin Square NY",
    "Subaru repair Franklin Square NY",
    "Kia repair Franklin Square NY",
    "Hyundai repair Franklin Square NY",
    "Jeep repair Franklin Square NY",
    "Dodge repair Franklin Square NY",
    "Ram truck repair Franklin Square NY",
    "Mini Cooper repair Franklin Square NY",
    "Porsche repair Franklin Square NY",
    "Acura repair Franklin Square NY",
    "Infiniti repair Franklin Square NY",
    "Mazda repair Franklin Square NY",
    "Volvo repair Franklin Square NY",
    "Lincoln repair Franklin Square NY",
    "Cadillac repair Franklin Square NY",
    "Buick repair Franklin Square NY",
    "Chrysler repair Franklin Square NY",
    "Toyota oil change Franklin Square",
    "Honda oil change Franklin Square",
    "Ford oil change Franklin Square",
    "BMW oil change Franklin Square",
    "Mercedes oil change Franklin Square",
    "Toyota brake repair NY",
    "Honda brake repair NY",
    "Ford brake repair NY",
    "BMW brake service NY",
    "Mercedes brake inspection NY",
    "transmission fluid change Toyota",
    "transmission repair Honda",
    "engine diagnostics BMW",
    "engine repair Mercedes",
    "suspension repair Toyota",
    "steering repair Honda",
    "tire rotation BMW",
    "wheel alignment Mercedes",
    "oil change near Hempstead NY",
    "brake repair near Valley Stream NY",
    "engine diagnostics near Elmont NY",
    "tire replacement near Garden City NY",
    "car inspection near Lynbrook NY",
    "emergency car repair near Rockville Centre NY",
    "affordable auto repair near West Hempstead NY",
    "full service auto repair near New Hyde Park NY",
    "best car mechanic near Merrick NY",
    "top rated mechanic near Freeport NY",
    "trusted auto shop near Oceanside NY",
    "auto repair near Levittown NY",
    "oil change Long Island NY",
    "brake service Long Island NY",
    "transmission repair Long Island NY",
    "suspension service Long Island NY",
    "wheel alignment Long Island NY",
    "tire service Long Island NY",
    "engine repair Long Island NY",
    "mechanic near me Long Island",
    "emergency car repair Long Island",
    "24 hour auto repair Long Island",
    "car AC repair Long Island NY",
    "heater repair Long Island NY",
    "radiator repair Long Island NY",
    "battery replacement Long Island NY",
    "alternator replacement Long Island NY",
    "starter replacement Long Island NY",
    "auto electrical repair Long Island NY",
    "check engine light diagnostics Long Island NY",
    "oil filter replacement Long Island NY",
    "fuel filter replacement Long Island NY",
    "spark plug replacement Long Island NY",
    "timing belt replacement Long Island NY",
    "brake pad replacement Long Island NY",
    "brake rotor resurfacing Long Island NY",
    "ABS repair Long Island NY",
    "shock absorber replacement Long Island NY",
    "strut replacement Long Island NY",
    "ball joint replacement Long Island NY",
    "tie rod replacement Long Island NY",
    "wheel alignment Long Island NY",
    "power steering repair Long Island NY",
    "suspension noise repair Long Island NY",
    "suspension inspection Long Island NY",
    "tire shop Long Island NY",
    "new tires Long Island",
    "tire mounting Long Island NY",
    "tire balancing Long Island NY",
    "flat tire repair Long Island NY",
    "winter tires Long Island",
    "rim repair Long Island NY",
    "tire rotation Long Island NY",
    "run-flat tire service Long Island NY",
    "preventative maintenance Long Island NY",
    "vehicle tune up Long Island NY",
    "coolant flush Long Island NY",
    "power steering fluid change Long Island NY",
    "transmission fluid change Long Island NY",
    "engine air filter replacement Long Island NY",
    "cabin filter replacement Long Island NY",
    "fuel filter replacement Long Island NY",
    "spark plug service Long Island NY",
    "starter replacement Long Island NY",
    "alternator repair Long Island NY",
    "battery testing Long Island NY",
    "electrical system diagnostics Long Island NY",
    "fuse box repair Long Island NY",
    "car wiring repair Long Island NY",
    "lighting repair Long Island NY",
    "auto AC recharge Long Island NY",
    "auto heating repair Long Island NY",
    "car AC compressor replacement Long Island NY",
    "blower motor repair Long Island NY",
    "heater core repair Long Island NY",
    "radiator flush Long Island NY",
    "coolant system service Long Island NY",
    "NY state inspection Long Island",
    "vehicle safety inspection Long Island",
    "emissions testing Long Island NY",
    "inspection station Long Island",
    "DOT inspection Long Island",
    "state certified mechanic Long Island NY",
    "auto body repair Long Island",
    "collision repair Long Island NY",
    "scratch and dent repair Long Island",
    "paint and refinishing Long Island",
    "frame alignment Long Island NY",
    "bumper repair Long Island NY",
    "fleet maintenance Long Island NY",
    "commercial vehicle repair Long Island",
    "truck repair Long Island NY",
    "van repair Long Island NY",
    "corporate fleet auto service Long Island NY",
    "winter car maintenance Long Island",
    "summer car maintenance Long Island",
    "road trip vehicle inspection Long Island NY",
    "seasonal tire change Long Island",
    "affordable auto repair Long Island NY",
    "trusted mechanic Long Island NY",
    "family-owned auto shop Long Island NY",
    "certified auto technician Long Island NY",
    "same day auto repair Long Island NY",
    "emergency car repair Long Island NY",
    "Everything Auto reviews Long Island NY",
    "Everything Auto phone number",
    "Everything Auto directions Long Island",
    "Everything Auto opening hours Long Island",
    "Everything Auto services list Long Island",
    "Everything Auto near me NY",
    "Everything Auto NY contact",
    "mechanic near me Queens NY",
    "mechanic near me Brooklyn NY",
    "mechanic near me Bronx NY",
    "mechanic near me Manhattan NY",
    "mechanic near me Staten Island NY",
    "engine repair Queens NY",
    "engine repair Brooklyn NY",
    "engine repair Bronx NY",
    "engine repair Manhattan NY",
    "engine repair Staten Island NY",
    "oil change Queens NY",
    "oil change Brooklyn NY",
    "oil change Bronx NY",
    "oil change Manhattan NY",
    "oil change Staten Island NY",
    "brake repair Queens NY",
    "brake repair Brooklyn NY",
    "brake repair Bronx NY",
    "brake repair Manhattan NY",
    "brake repair Staten Island NY",
    "transmission repair Queens NY",
    "transmission repair Brooklyn NY",
    "transmission repair Bronx NY",
    "transmission repair Manhattan NY",
    "transmission repair Staten Island NY",
    "suspension repair Queens NY",
    "suspension repair Brooklyn NY",
    "suspension repair Bronx NY",
    "suspension repair Manhattan NY",
    "suspension repair Staten Island NY",
    "steering repair Queens NY",
    "steering repair Brooklyn NY",
    "steering repair Bronx NY",
    "steering repair Manhattan NY",
    "steering repair Staten Island NY",
    "tire rotation Queens NY",
    "tire rotation Brooklyn NY",
    "tire rotation Bronx NY",
    "tire rotation Manhattan NY",
    "tire rotation Staten Island NY",
    "wheel alignment Queens NY",
    "wheel alignment Brooklyn NY",
    "wheel alignment Bronx NY",
    "wheel alignment Manhattan NY",
    "wheel alignment Staten Island NY",
    "auto body repair Queens NY",
    "auto body repair Brooklyn NY",
    "auto body repair Bronx NY",
    "auto body repair Manhattan NY",
    "auto body repair Staten Island NY",
    "collision repair Queens NY",
    "collision repair Brooklyn NY",
    "collision repair Bronx NY",
    "collision repair Manhattan NY",
    "collision repair Staten Island NY",
    "brake inspection Queens NY",
    "brake inspection Brooklyn NY",
    "brake inspection Bronx NY",
    "brake inspection Manhattan NY",
    "brake inspection Staten Island NY",
    "engine diagnostics Queens NY",
    "engine diagnostics Brooklyn NY",
    "engine diagnostics Bronx NY",
    "engine diagnostics Manhattan NY",
    "engine diagnostics Staten Island NY",
    "oil filter replacement Queens NY",
    "oil filter replacement Brooklyn NY",
    "oil filter replacement Bronx NY",
    "oil filter replacement Manhattan NY",
    "oil filter replacement Staten Island NY",
    "car AC recharge Queens NY",
    "car AC recharge Brooklyn NY",
    "car AC recharge Bronx NY",
    "car AC recharge Manhattan NY",
    "car AC recharge Staten Island NY",
    "mechanic shop near me NY",
    "auto repair near me NY",
    "car service center NY",
    "vehicle maintenance NY",
    "auto care NY",
    "NY auto repair experts",
    "NY car mechanic services",
    "Franklin Square car service",
    "Franklin Square auto care",
    "Franklin Square mechanic reviews",
    "NY auto repair quotes",
    "NY vehicle repair specialists",
    "auto repair discounts NY",
    "Everything Auto auto shop NY",
    "Everything Auto service Franklin Square",
    "Everything Auto NY reviews",
    "top auto repair NY",
    "best mechanic Franklin Square NY",
    "affordable brake service NY",
    "affordable engine repair NY",
    "emergency transmission repair NY",
    "trusted suspension repair NY",
    "NY steering service experts",
    "wheel repair Franklin Square",
    "tire balancing Franklin Square NY",
    "engine diagnostics Franklin Square",
    "oil change service NY",
    "full service mechanic Franklin Square",
    "auto shop hours Franklin Square",
    "Everything Auto directions NY",
    "Everything Auto phone Franklin Square",
    "Everything Auto near me Franklin Square",
    "auto repair Franklin Square family owned",
    "NY car repair emergency",
    "NY brake service appointment",
    "NY oil change coupon",
    "NY car diagnostics appointment",
    "NY auto inspection Franklin Square",
    "NY certified mechanic Franklin Square",
    "NY transmission repair specialists",
    "NY suspension repair experts",
    "NY tire shop Franklin Square",
    "NY wheel alignment service",
    "NY engine repair Franklin Square",
    "NY brake repair Franklin Square",
    "NY transmission fluid service",
    "NY oil change Franklin Square",
    "NY steering repair Franklin Square",
    "NY auto maintenance experts",
    "NY car AC repair service",
    "NY engine performance check Franklin Square",
    "NY radiator repair Franklin Square",
    "NY car battery replacement Franklin Square",
    "NY auto electrical diagnostics",
    "NY vehicle inspection Franklin Square",
    "NY auto tune up Franklin Square",
    "NY vehicle maintenance Franklin Square",
    "NY auto repair Franklin Square reviews",
    "NY brake pad replacement Franklin Square",
    "NY tire rotation Franklin Square",
    "NY shock and strut replacement Franklin Square",
    "NY auto repair shop Franklin Square",
    "NY car repair service Franklin Square",
    "NY engine oil change Franklin Square",
    "NY full service auto repair Franklin Square",
    "NY professional mechanics Franklin Square",
    "NY brake inspection Franklin Square",
    "NY emergency car repair Franklin Square",
    "NY transmission diagnostics Franklin Square",
    "NY vehicle diagnostic testing Franklin Square",
    "NY auto repair Long Island",
    "NY Everything Auto Franklin Square",
    "NY Everything Auto Franklin Square contact",
    "NY car repair near me Franklin Square",
    "NY trusted auto repair Franklin Square",
    "NY auto repair estimates Franklin Square",
    "NY Everything Auto auto services",
    "NY car inspection Franklin Square",
    "NY vehicle safety inspection Franklin Square",
    "NY Everything Auto phone number",
    "NY Everything Auto directions",
    "NY Everything Auto opening hours",
    // Additional 1000 unique keywords
    "Alfa Romeo repair Franklin Square NY",
    "Aston Martin repair Franklin Square NY",
    "Bentley repair Franklin Square NY",
    "Bugatti repair Franklin Square NY",
    "Cadillac service Franklin Square NY",
    "Chevrolet oil change Franklin Square NY",
    "Chrysler transmission repair Franklin Square NY",
    "Dodge brake repair Franklin Square NY",
    "Fiat repair Franklin Square NY",
    "Ford engine repair Franklin Square NY",
    "Genesis repair Franklin Square NY",
    "Honda transmission service Franklin Square NY",
    "Hyundai brake inspection Franklin Square NY",
    "Infiniti oil change Franklin Square NY",
    "Jaguar repair Franklin Square NY",
    "Jeep tire rotation Franklin Square NY",
    "Kia wheel alignment Franklin Square NY",
    "Lamborghini repair Franklin Square NY",
    "Land Rover repair Franklin Square NY",
    "Lexus brake replacement Franklin Square NY",
    "Maserati repair Franklin Square NY",
    "Maybach repair Franklin Square NY",
    "McLaren repair Franklin Square NY",
    "Mini Cooper oil change Franklin Square NY",
    "Mitsubishi repair Franklin Square NY",
    "Nissan brake service Franklin Square NY",
    "Pagani repair Franklin Square NY",
    "Porsche transmission repair Franklin Square NY",
    "Ram truck brake repair Franklin Square NY",
    "Rolls Royce repair Franklin Square NY",
    "Subaru oil change Franklin Square NY",
    "Tesla battery replacement Franklin Square NY",
    "Toyota suspension repair Franklin Square NY",
    "Volkswagen engine repair Franklin Square NY",
    "Volvo tire service Franklin Square NY",
    "used car inspection Franklin Square NY",
    "pre-purchase car inspection Franklin Square NY",
    "fleet car maintenance Franklin Square NY",
    "commercial vehicle repair Franklin Square NY",
    "truck maintenance Franklin Square NY",
    "van maintenance Franklin Square NY",
    "engine tune-up Franklin Square NY",
    "brake fluid replacement Franklin Square NY",
    "automatic transmission repair Franklin Square NY",
    "manual transmission repair Franklin Square NY",
    "CVT transmission service Franklin Square NY",
    "dual clutch transmission repair Franklin Square NY",
    "drivetrain service Franklin Square NY",
    "differential repair Franklin Square NY",
    "axle repair Franklin Square NY",
    "clutch replacement Franklin Square NY",
    "timing chain replacement Franklin Square NY",
    "timing belt service Franklin Square NY",
    "engine overhaul Franklin Square NY",
    "engine rebuild Franklin Square NY",
    "turbocharger repair Franklin Square NY",
    "supercharger service Franklin Square NY",
    "fuel injection repair Franklin Square NY",
    "injector cleaning Franklin Square NY",
    "fuel pump replacement Franklin Square NY",
    "air conditioning service Franklin Square NY",
    "AC recharge Franklin Square NY",
    "heater repair Franklin Square NY",
    "radiator replacement Franklin Square NY",
    "coolant system repair Franklin Square NY",
    "thermostat replacement Franklin Square NY",
    "fan clutch repair Franklin Square NY",
    "cooling fan replacement Franklin Square NY",
    "battery test Franklin Square NY",
    "alternator test Franklin Square NY",
    "starter test Franklin Square NY",
    "starter repair Franklin Square NY",
    "alternator replacement Franklin Square NY",
    "battery installation Franklin Square NY",
    "charging system repair Franklin Square NY",
    "engine computer diagnostics Franklin Square NY",
    "ECU repair Franklin Square NY",
    "engine control module service Franklin Square NY",
    "O2 sensor replacement Franklin Square NY",
    "mass airflow sensor repair Franklin Square NY",
    "throttle body cleaning Franklin Square NY",
    "timing sensor replacement Franklin Square NY",
    "vehicle emission testing Franklin Square NY",
    "smog inspection Franklin Square NY",
    "exhaust repair Franklin Square NY",
    "muffler replacement Franklin Square NY",
    "catalytic converter replacement Franklin Square NY",
    "tailpipe repair Franklin Square NY",
    "exhaust manifold repair Franklin Square NY",
    "emissions control repair Franklin Square NY",
    "brake pad installation Franklin Square NY",
    "brake rotor replacement Franklin Square NY",
    "brake caliper repair Franklin Square NY",
    "ABS system service Franklin Square NY",
    "electronic parking brake repair Franklin Square NY",
    "suspension inspection Franklin Square NY",
    "shock absorber service Franklin Square NY",
    "strut replacement Franklin Square NY",
    "coil spring replacement Franklin Square NY",
    "control arm repair Franklin Square NY",
    "ball joint replacement Franklin Square NY",
    "tie rod end replacement Franklin Square NY",
    "sway bar repair Franklin Square NY",
    "steering rack replacement Franklin Square NY",
    "power steering pump repair Franklin Square NY",
    "steering fluid flush Franklin Square NY",
    "tire repair Franklin Square NY",
    "flat tire service Franklin Square NY",
    "wheel balancing Franklin Square NY",
    "tire mounting Franklin Square NY",
    "wheel replacement Franklin Square NY",
    "alloy wheel repair Franklin Square NY",
    "rim straightening Franklin Square NY",
    "wheel alignment Franklin Square NY",
    "four wheel alignment Franklin Square NY",
    "two wheel alignment Franklin Square NY",
    "computerized wheel alignment Franklin Square NY",
    "laser wheel alignment Franklin Square NY",
    "oil change service Franklin Square NY",
    "synthetic oil change Franklin Square NY",
    "full synthetic oil change Franklin Square NY",
    "oil filter replacement Franklin Square NY",
    "engine oil inspection Franklin Square NY",
    "car tune-up Franklin Square NY",
    "vehicle inspection Franklin Square NY",
    "NY state car inspection Franklin Square",
    "DOT inspection Franklin Square NY",
    "pre-trip vehicle inspection Franklin Square NY",
    "roadside assistance Franklin Square NY",
    "emergency car service Franklin Square NY",
    "24 hour mechanic Franklin Square NY",
    "mobile mechanic Franklin Square NY",
    "on-site car repair Franklin Square NY",
    "vehicle diagnostics Franklin Square NY",
    "computer diagnostics Franklin Square NY",
    "check engine light service Franklin Square NY",
    "car noise diagnostics Franklin Square NY",
    "engine knocking repair Franklin Square NY",
    "engine overheating repair Franklin Square NY",
    "oil leak repair Franklin Square NY",
    "coolant leak repair Franklin Square NY",
    "transmission leak repair Franklin Square NY",
    "power steering leak repair Franklin Square NY",
    "brake fluid leak repair Franklin Square NY",
    "tire pressure monitoring system repair Franklin Square NY",
    "car alarm repair Franklin Square NY",
    "remote key repair Franklin Square NY",
    "key fob replacement Franklin Square NY",
    "door lock repair Franklin Square NY",
    "window regulator repair Franklin Square NY",
    "power window repair Franklin Square NY",
    "sunroof repair Franklin Square NY",
    "roof rack installation Franklin Square NY",
    "windshield replacement Franklin Square NY",
    "windshield chip repair Franklin Square NY",
    "headlight replacement Franklin Square NY",
    "taillight replacement Franklin Square NY",
    "fog light installation Franklin Square NY",
    "LED light installation Franklin Square NY",
    "vehicle lighting diagnostics Franklin Square NY",
    "interior light repair Franklin Square NY",
    "dashboard light repair Franklin Square NY",
    "instrument cluster repair Franklin Square NY",
    "car stereo installation Franklin Square NY",
    "speaker replacement Franklin Square NY",
    "navigation system repair Franklin Square NY",
    "backup camera repair Franklin Square NY",
    "parking sensor repair Franklin Square NY",
    "rear view camera installation Franklin Square NY",
    "remote start installation Franklin Square NY",
    "keyless entry repair Franklin Square NY",
    "car detailing Franklin Square NY",
    "interior car cleaning Franklin Square NY",
    "exterior car cleaning Franklin Square NY",
    "paint protection Franklin Square NY",
    "ceramic coating Franklin Square NY",
    "vehicle waxing Franklin Square NY",
    "car polishing Franklin Square NY",
    "headlight restoration Franklin Square NY",
    "car scratch repair Franklin Square NY",
    "minor dent repair Franklin Square NY",
    "full body paint Franklin Square NY",
    "collision repair Franklin Square NY",
    "bumpers repair Franklin Square NY",
    "frame straightening Franklin Square NY",
    "insurance claims auto repair Franklin Square NY",
    "NY auto body shop Franklin Square",
    "car accident repair Franklin Square NY",
    "auto painting Franklin Square NY",
    "auto refinishing Franklin Square NY",
    "paint touch up Franklin Square NY",
    "paint blending Franklin Square NY",
    "paint color matching Franklin Square NY",
    "paintless dent removal Franklin Square NY",
    "vehicle restoration Franklin Square NY",
    "classic car repair Franklin Square NY",
    "antique car repair Franklin Square NY",
    "vintage car repair Franklin Square NY",
    "car rust repair Franklin Square NY",
    "underbody repair Franklin Square NY",
    "chassis repair Franklin Square NY",
    "frame repair Franklin Square NY",
    "car fabrication Franklin Square NY",
    "custom car modification Franklin Square NY",
    "performance tuning Franklin Square NY",
    "engine tuning Franklin Square NY",
    "ECU tuning Franklin Square NY",
    "chip tuning Franklin Square NY",
    "dyno tuning Franklin Square NY",
    "exhaust tuning Franklin Square NY",
    "turbo tuning Franklin Square NY",
    "supercharger tuning Franklin Square NY",
    "performance upgrades Franklin Square NY",
    "aftermarket parts installation Franklin Square NY",
    "custom wheels Franklin Square NY",
    "custom tires Franklin Square NY",
    "performance brakes Franklin Square NY",
    "performance suspension Franklin Square NY",
    "performance steering Franklin Square NY",
    "track car service Franklin Square NY",
    "race car maintenance Franklin Square NY",
    "high performance car repair Franklin Square NY",
    "luxury car service Franklin Square NY",
    "exotic car repair Franklin Square NY",
    "sports car repair Franklin Square NY",
    "convertible car repair Franklin Square NY",
    "SUV repair Franklin Square NY",
    "crossover repair Franklin Square NY",
    "minivan repair Franklin Square NY",
    "pickup truck repair Franklin Square NY",
    "heavy duty truck repair Franklin Square NY",
    "fleet vehicle service Franklin Square NY",
    "commercial truck repair Franklin Square NY",
    "diesel engine repair Franklin Square NY",
    "gasoline engine repair Franklin Square NY",
    "hybrid car repair Franklin Square NY",
    "electric car repair Franklin Square NY",
    "plug-in hybrid repair Franklin Square NY",
    "EV battery replacement Franklin Square NY",
    "electric motor repair Franklin Square NY",
    "regenerative braking repair Franklin Square NY",
    "EV charging system repair Franklin Square NY",
    "hybrid system diagnostics Franklin Square NY",
    "EV maintenance Franklin Square NY",
    "eco car repair Franklin Square NY",
    "green car service Franklin Square NY",
    "sustainable car repair Franklin Square NY",
    "NY auto service Franklin Square reviews",
    "NY car repair Franklin Square reviews",
    "Everything Auto Franklin Square feedback",
    "Everything Auto Franklin Square ratings",
    "Everything Auto Franklin Square testimonials",
    "Everything Auto Franklin Square customer reviews",
    "Everything Auto Franklin Square repair history",
    "Everything Auto Franklin Square certified repair",
    "Everything Auto Franklin Square trusted mechanic",
    "Everything Auto Franklin Square full service",
    "Everything Auto Franklin Square oil change",
    "Everything Auto Franklin Square brake repair",
    "Everything Auto Franklin Square transmission repair",
    "Everything Auto Franklin Square tire service",
    "Everything Auto Franklin Square suspension repair",
    "Everything Auto Franklin Square steering repair",
    "Everything Auto Franklin Square AC service",
    "Everything Auto Franklin Square radiator repair",
    "Everything Auto Franklin Square engine repair",
    "Everything Auto Franklin Square battery replacement",
    "Everything Auto Franklin Square electrical repair",
    "Everything Auto Franklin Square diagnostics",
    "Everything Auto Franklin Square maintenance plan",
    "Everything Auto Franklin Square preventive care",
    "Everything Auto Franklin Square 24/7 service",
    "Everything Auto Franklin Square emergency repair",
    "Everything Auto Franklin Square certified technicians",
    "Everything Auto Franklin Square trusted auto shop",
    "Everything Auto Franklin Square full diagnostics",
    "Everything Auto Franklin Square inspection services",
    "Everything Auto Franklin Square NY contact",
    "Everything Auto Franklin Square NY directions",
    "Everything Auto Franklin Square NY phone",
    "Everything Auto Franklin Square NY hours",
    "Everything Auto Franklin Square NY website",
    "Everything Auto Franklin Square NY services list",
    "Everything Auto Franklin Square NY coupons",
    "Everything Auto Franklin Square NY specials",
    "Everything Auto Franklin Square NY appointments",
    "Everything Auto Franklin Square NY scheduling",
    "Everything Auto Franklin Square NY certified",
    "Everything Auto Franklin Square NY experienced mechanics",
    "Everything Auto Franklin Square NY honest service",
    "Everything Auto Franklin Square NY reliable auto repair",
    "Everything Auto Franklin Square NY trusted car repair",
    "Everything Auto Franklin Square NY family-owned",
    "Everything Auto Franklin Square NY local auto shop",
    "Everything Auto Franklin Square NY professional services",
    "Everything Auto Franklin Square NY complete vehicle maintenance",
    "Everything Auto Franklin Square NY all makes models",
    "Everything Auto Franklin Square NY shop tour",
    "Everything Auto Franklin Square NY customer testimonials",
    "Everything Auto Franklin Square NY vehicle diagnostics",
    "Everything Auto Franklin Square NY tire rotation",
    "Everything Auto Franklin Square NY brake inspection",
    "Everything Auto Franklin Square NY engine diagnostics",
    "Everything Auto Franklin Square NY transmission diagnostics",
    "Everything Auto Franklin Square NY oil change service",
    "Everything Auto Franklin Square NY steering service",
    "Everything Auto Franklin Square NY suspension service",
    "Everything Auto Franklin Square NY wheel alignment",
    "Everything Auto Franklin Square NY tire repair",
    "Everything Auto Franklin Square NY auto repair estimates",
    "Everything Auto Franklin Square NY repair quotes",
    "Everything Auto Franklin Square NY auto service reviews",
    "Everything Auto Franklin Square NY customer satisfaction"


  ],

  openGraph: {
    title: "Everything Auto - Expert Auto Repair in Franklin Square, NY",
    description:
      "Trusted Auto Repair Shop in Franklin Square, NY. Family-Owned Since 2008. Quality Service for All Makes & Models. Call (516) 775-9724 Today!",
    url: "https://everythingauto.com",
    siteName: "Everything Auto",
    images: [
      {
        url: "/favicon.svg",
        width: 1200,
        height: 630,
        alt: "Everything Auto Franklin Square NY",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  alternates: {
    canonical: "https://everythingauto.com",
  }
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <Script
          src="https://elevenlabs.io/convai-widget/convai-widget.js"
          strategy="beforeInteractive"
        />
        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-D70YTM9YH6"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-D70YTM9YH6');
          `}
        </Script>
        <Script
          id="localbusiness-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "AutoRepair",
              name: "Everything Auto",
              image: "https://everythingauto.com/favicon.svg",
              "@id": "https://everythingauto.com",
              url: "https://everythingauto.com",
              telephone: "+1-516-555-1234",
              address: {
                "@type": "PostalAddress",
                streetAddress: "123 Main Street",
                addressLocality: "Franklin Square",
                addressRegion: "NY",
                postalCode: "11010",
                addressCountry: "US",
              },
              openingHours: "Mo-Fr 08:00-18:00",
              priceRange: "$$",
            }),
          }}
        />
{/* ✅ Google Tag Manager */}
        <Script id="gtm-init" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-5R3HBFRX');
          `}
        </Script>
        {/* End GTM */}
      </head>
      <body className={inter.className}>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-5R3HBFRX"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
