import Blog from "./components/Blog";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auto Care Blog | Everything Auto - Franklin Square",
  description:
    "Read expert auto care tips, maintenance guides, repair advice, and updates from Everything Auto in Franklin Square, NY. Stay informed about car care, safety, and performance.",
  keywords: [
    "auto care blog",
    "car maintenance tips",
    "vehicle repair advice",
    "car troubleshooting guide",
    "auto repair insights",
    "Long Island car maintenance",
    "Everything Auto blog",
    "Franklin Square auto repair tips",
    "brake maintenance advice",
    "oil change information",
    "tire maintenance guide",
    "winter car care checklist",
    "car air conditioning tips",
    "vehicle battery care",
    "check engine light solutions",
    "car safety tips Long Island",
    "how to extend car life",
    "auto technician advice",
    "DIY car care basics",
    "how to maintain your car",
    "auto service knowledge base",
    "engine performance tips",
    "auto maintenance checklist",
    "why regular service matters",
    "best time for oil change",
    "how to check tire pressure",
    "brake pad replacement signs",
    "auto repair education",
    "car electrical system tips",
    "vehicle health signs",
    "auto care awareness",
    "seasonal car maintenance",
    "AC repair information",
    "car engine overheating causes",
    "auto battery replacement guide",
    "alternator vs battery issues",
    "car won’t start causes",
    "how to avoid engine damage",
    "fuel efficiency maintenance",
    "eco-friendly driving habits",
    "tire rotation importance",
    "car fluid check schedule",
    "how to choose motor oil",
    "engine oil types explained",
    "synthetic vs conventional oil",
    "auto repair news Long Island",
    "Everything Auto insights",
    "car parts education",
    "auto diagnostics explained",
    "how to spot brake wear",
    "AC recharge information",
    "check engine light meaning",
    "how to prevent battery drain",
    "car maintenance Long Island",
    "trusted auto care Franklin Square",
    "affordable car service tips",
    "road safety preparation",
    "auto mechanic recommendations",
    "vehicle service reminders",
    "auto service intervals",
    "best practices for car care",
    "regular maintenance benefits",
    "auto fluid guide",
    "preventative car maintenance",
    "car care checklist Franklin Square",
    "top signs of car trouble",
    "auto repair basics for beginners",
    "understanding car noises",
    "how to maintain brakes",
    "auto battery lifespan tips",
    "tire wear patterns explained",
    "importance of wheel alignment",
    "when to replace car tires",
    "how to keep car AC cold",
    "auto repair near Franklin Square",
    "trusted mechanic Long Island",
    "auto care professionals NY",
    "vehicle safety checks",
    "car tune-up tips",
    "auto engine diagnostics Long Island",
    "car overheating prevention",
    "auto maintenance myths",
    "car electrical repair guide",
    "auto inspection tips",
    "vehicle performance optimization",
    "how to prepare car for road trip",
    "auto service blog Franklin Square",
    "Long Island automotive tips",
    "vehicle maintenance education",
    "auto care resource",
    "auto workshop updates",
    "Everything Auto service blog",
    "best auto maintenance advice",
    "auto repair troubleshooting guide",
    "how to care for your vehicle",
    "car AC service Long Island",
    "auto battery care tips",
    "brake system maintenance blog",
    "auto service awareness Franklin Square",
    "Everything Auto expert blog"
  ],
  openGraph: {
    title: "Auto Care Blog | Everything Auto - Franklin Square",
    description:
      "Explore the Everything Auto Blog for expert advice on maintenance, repair, and car care from professional technicians in Franklin Square, NY.",
    url: "https://everythingauto.com/blog",
    siteName: "Everything Auto",
    images: [
      {
        url: "/Blog.jpg",
        width: 1200,
        height: 630,
        alt: "Everything Auto Blog Franklin Square NY",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  metadataBase: new URL("https://everythingauto.com"),
};

export default async function Home() {
  return (
    <>
      <Blog />
    </>
  );
}
