import { Metadata } from "next";
import ReviewsPage from "./components/Reviews";

export const metadata : Metadata= {
  title: "Customer Testimonials & Google Reviews | Everything Auto Franklin Square",
  description:
    "Read genuine 5-star customer reviews and testimonials about Everything Auto in Franklin Square. Discover why over 5,000 clients trust our expert car repair and maintenance services since 2008.",
  keywords: `
Everything Auto Franklin Square reviews,
Everything Auto testimonials,
car repair reviews Franklin Square,
best auto repair shop Franklin Square,
5 star auto service Franklin Square,
customer feedback car repair,
trusted mechanics Franklin Square,
automotive service reviews,
best mechanic near me,
Franklin Square vehicle maintenance,
oil change reviews,
tire rotation service reviews,
brake service Franklin Square,
engine repair reviews,
transmission service Franklin Square,
diagnostic service Franklin Square,
preventative maintenance reviews,
auto AC repair reviews,
suspension repair Franklin Square,
wheel alignment Franklin Square,
vehicle inspection reviews,
auto detailing Franklin Square,
car tune-up reviews,
certified mechanics Franklin Square,
New York auto repair shop,
local car repair testimonials,
satisfied auto customers,
car maintenance feedback,
professional car repair Franklin Square,
reliable mechanic near me,
honest auto repair shop,
vehicle diagnostics reviews,
full-service auto shop Franklin Square,
automotive repair customer reviews,
Everything Auto Google ratings,
Everything Auto feedback,
vehicle service testimonials,
repair quality reviews Franklin Square,
engine tune-up Franklin Square,
experienced auto technicians,
automotive customer experience,
car maintenance experts Franklin Square,
repair satisfaction reviews,
car service reputation Franklin Square,
best rated auto shop Franklin Square,
top auto repair reviews Long Island,
brake replacement testimonials,
vehicle care reviews Franklin Square,
Everything Auto ratings,
engine performance feedback,
auto workshop Franklin Square reviews,
car diagnostic service reviews,
automotive repair ratings,
Everything Auto customer stories,
happy car repair clients,
trusted vehicle service Franklin Square,
tire balancing reviews,
oil filter replacement Franklin Square,
car AC service feedback,
auto maintenance trust reviews,
ASE certified mechanics reviews,
car inspection Franklin Square testimonials,
best auto technicians NY,
reliable repair Franklin Square,
check engine light service reviews,
exhaust system repair Franklin Square,
professional car services reviews,
affordable auto repair Franklin Square,
5 star mechanic reviews NY,
luxury vehicle repair reviews,
truck repair Franklin Square,
SUV maintenance reviews,
best mechanic shop Nassau County,
car battery replacement reviews,
alternator repair Franklin Square,
coolant flush reviews,
timing belt replacement Franklin Square,
car service satisfaction reviews,
local car shop reviews,
customer service excellence auto repair,
genuine mechanic feedback Franklin Square,
professional diagnostic center reviews,
Everything Auto excellence,
automotive expertise reviews,
engine light diagnosis Franklin Square,
electrical repair reviews,
car heating repair Franklin Square,
NY auto maintenance reviews,
auto service near Franklin Square,
car performance improvement feedback,
wheel balancing Franklin Square,
steering repair testimonials,
radiator repair Franklin Square,
automotive trust Franklin Square,
client experience Everything Auto,
car repair reputation NY,
tune-up Franklin Square,
transmission flush reviews,
car air conditioning service Franklin Square,
hybrid vehicle repair reviews,
vehicle reliability Franklin Square,
honest car service reviews,
licensed mechanics Franklin Square,
skilled auto repair technicians,
top mechanic reviews Franklin Square,
fuel system service reviews,
auto care satisfaction NY,
customer experience Franklin Square auto,
fast car repair reviews,
efficient mechanic Franklin Square,
quality workmanship auto repair,
loyal auto repair customers,
modern diagnostics Franklin Square,
family-owned auto repair NY,
Everything Auto 5-star experience,
long-term customer trust Franklin Square,
positive car service reviews,
repeat customers Everything Auto,
best local mechanic Franklin Square,
emergency auto repair reviews,
roadside assistance Franklin Square reviews,
trusted auto experts NY,
quick oil change Franklin Square reviews,
dependable car repair Franklin Square,
professional vehicle service feedback,
automotive excellence Franklin Square,
car service quality feedback,
maintenance excellence Franklin Square,
top-rated automotive shop Franklin Square,
expert car technicians NY,
Everything Auto best reviews,
reputable auto shop Franklin Square,
vehicle repair near Franklin Square NY,
service satisfaction testimonials,
top Franklin Square mechanics,
5 star client testimonials Franklin Square,
automotive feedback New York,
car repair ratings Franklin Square,
honest mechanic reviews NY,
Everything Auto success stories,
best car repair testimonials,
high-quality car service reviews,
customer confidence Franklin Square auto,
service reliability Everything Auto,
highly reviewed auto repair NY,
Everything Auto trusted mechanics,
verified car service reviews Franklin Square,
Everything Auto client praise,
customer appreciation auto repair,
vehicle repair shop testimonials Franklin Square,
long-standing customers reviews,
trusted auto professionals Franklin Square NY
  `,
};

export default async function Home() {
  return (
    <>
      <ReviewsPage />
    </>
  );
}
