import { Metadata } from "next";
import PreventativeMaintenance from "./components/PreventativeMaintenance";

export const metadata: Metadata = {
  title: "Preventative Maintenance in Franklin Square, NY | Everything Auto",
  description:
    "Keep your car running smoothly with professional preventative maintenance services in Franklin Square, NY. Trusted by drivers across Nassau County for reliable auto care.",
  keywords: [
    "preventative maintenance Franklin Square NY",
    "car maintenance Franklin Square",
    "vehicle maintenance Franklin Square",
    "auto service Franklin Square NY",
    "routine car maintenance",
    "Everything Auto maintenance service",
    "scheduled car service Franklin Square",
    "vehicle inspection Franklin Square",
    "auto tune-up Franklin Square",
    "preventive maintenance Nassau County",
    "oil change and filter replacement",
    "car tune up Franklin Square",
    "car fluid replacement service",
    "vehicle reliability service",
    "spark plug replacement Franklin Square",
    "timing belt service Nassau County",
    "engine maintenance Franklin Square",
    "car filter replacement Franklin Square",
    "brake fluid change Franklin Square",
    "coolant flush service",
    "transmission fluid change Franklin Square",
    "power steering fluid change",
    "differential fluid service",
    "engine air filter replacement",
    "cabin filter change",
    "fuel filter replacement Franklin Square",
    "regular vehicle maintenance NY",
    "best auto shop Franklin Square",
    "affordable car maintenance",
    "auto service near me",
    "routine maintenance Franklin Square",
    "factory scheduled maintenance",
    "car check-up service",
    "preventative car care",
    "auto repair and maintenance Franklin Square",
    "vehicle performance check",
    "auto health inspection",
    "trusted mechanic Franklin Square",
    "Everything Auto Franklin Square",
    "ASE certified mechanics Franklin Square",
    "car diagnostics and maintenance",
    "engine service Franklin Square NY",
    "transmission check Franklin Square",
    "tire rotation and maintenance",
    "wheel alignment Franklin Square",
    "car tune-up near me",
    "top auto repair shop Franklin Square",
    "local auto service Nassau County",
    "best auto maintenance Long Island",
    "auto repair near Hempstead",
    "auto service near Elmont",
    "auto shop near Garden City",
    "auto maintenance near Valley Stream",
    "Nassau County auto repair center",
    "comprehensive vehicle maintenance",
    "car reliability improvement service",
    "prevent breakdown service",
    "car performance tuning",
    "auto maintenance packages",
    "check engine diagnostics",
    "regular check-up for cars",
    "Franklin Square mechanic near me",
    "reliable car service Franklin Square",
    "maintenance service for all makes",
    "professional car care Franklin Square",
    "maintenance checklist service",
    "routine inspection and tune-up",
    "oil and filter change Franklin Square",
    "fluid top-up service",
    "auto preventive maintenance NY",
    "vehicle service schedule management",
    "engine performance maintenance",
    "car maintenance plan Nassau County",
    "preventative car service Franklin Square",
    "affordable vehicle inspection",
    "complete vehicle tune-up service",
    "maintenance for hybrid cars",
    "eco-friendly car maintenance",
    "luxury car maintenance Franklin Square",
    "foreign car maintenance experts",
    "domestic vehicle maintenance",
    "routine maintenance near me",
    "car inspection and maintenance",
    "auto check and tune service",
    "engine cleaning and tune-up",
    "oil change plus inspection service",
    "long island preventative maintenance",
    "Everything Auto repair shop",
    "full service auto shop Franklin Square",
    "vehicle longevity service",
    "preventative maintenance packages",
    "auto health report service",
    "digital vehicle inspection Franklin Square",
    "brake inspection and maintenance",
    "suspension check Franklin Square",
    "battery check and replacement",
    "headlight inspection service",
    "vehicle safety inspection Nassau County",
    "air filter and spark plug service",
    "engine care and maintenance Franklin Square",
    "transmission fluid replacement NY",
    "timing belt inspection Franklin Square",
    "preventative service for new cars",
    "high mileage car maintenance",
    "fleet maintenance service Franklin Square",
    "auto preventive care Franklin Square",
    "affordable scheduled maintenance",
    "car health check Nassau County",
    "auto mechanic Franklin Square NY",
    "prevent costly repairs Franklin Square",
    "long-term vehicle protection service",
    "factory recommended service intervals",
    "maintenance schedule check",
    "Franklin Square service center",
    "trusted automotive service NY",
    "routine engine maintenance Franklin Square",
    "coolant system maintenance",
    "engine oil and filter service",
    "comprehensive maintenance inspection",
    "car reliability improvement Franklin Square",
    "best rated auto shop Nassau County",
    "Everything Auto preventive service",
    "local mechanic Franklin Square NY",
    "quick car maintenance service",
    "preventative auto service Long Island",
    "NYS vehicle care Franklin Square",
    "top rated auto maintenance Franklin Square",
    "engine fluid service Nassau County",
    "battery and alternator maintenance",
    "vehicle health monitoring Franklin Square",
    "auto maintenance deals Franklin Square",
    "auto care family business Nassau County",
    "certified vehicle inspection service",
    "safety and performance maintenance",
    "auto system check-up",
    "brake system maintenance Franklin Square",
    "steering system maintenance",
    "suspension and shocks maintenance",
    "belts and hoses inspection Franklin Square",
    "comprehensive maintenance Franklin Square NY",
    "routine auto inspection and care",
    "vehicle tune-up Franklin Square",
    "preventative maintenance check Nassau County",
    "Everything Auto Franklin Square NY",
    "affordable vehicle service",
    "car repair and maintenance Long Island",
    "auto repair shop Franklin Square NY",
    "preventative maintenance specialists",
    "vehicle service center Franklin Square",
    "engine diagnostics Franklin Square NY",
    "preventative maintenance program",
    "reliable vehicle service Franklin Square",
    "top mechanics Franklin Square",
    "auto shop open near me Franklin Square",
    "routine vehicle check Franklin Square NY",
    "best preventative maintenance Franklin Square",
    "long island auto service experts",
    "trusted car service Nassau County",
    "preventative service you can trust"
  ],
  openGraph: {
    title: "Preventative Maintenance in Franklin Square, NY | Everything Auto",
    description:
      "Everything Auto offers top-quality preventative maintenance in Franklin Square, NY — from oil changes to timing belts, we keep your vehicle reliable and safe.",
    url: "https://everythingauto.com/preventative-maintenance",
    siteName: "Everything Auto",
    images: [
      {
        url: "https://images.unsplash.com/photo-1553754592-a694d6932760?w=1200&h=600&fit=crop",
        width: 1200,
        height: 600,
        alt: "Preventative Maintenance Franklin Square NY",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default async function Home() {
  return (
    <>
      <PreventativeMaintenance />
    </>
  );
}
