import { Metadata } from "next";
import Videos from "./components/Videos";

export const metadata : Metadata = {
  title: "Everything Auto Videos | Customer Testimonials & Shop Insights - Franklin Square NY",
  description:
    "Watch Everything Auto videos — customer testimonials, shop tours, diagnostic demos, and car care tutorials. Discover trusted auto repair experts in Franklin Square, NY.",
  keywords: [
    "everything auto videos",
    "auto repair shop videos",
    "franklin square auto repair videos",
    "auto service testimonials",
    "car repair testimonials",
    "auto repair customer reviews",
    "auto shop video gallery",
    "everything auto youtube",
    "auto maintenance tutorials",
    "car care tips videos",
    "brake service videos",
    "engine diagnostics videos",
    "auto diagnostics explained",
    "digital vehicle inspection demo",
    "auto inspection process",
    "car service transparency",
    "auto mechanic testimonials",
    "customer testimonial video",
    "everything auto review",
    "auto shop virtual tour",
    "auto repair behind the scenes",
    "auto repair experts",
    "transmission repair videos",
    "oil change demonstration",
    "car maintenance routine",
    "auto repair education",
    "vehicle maintenance guide",
    "mechanic shop video",
    "trusted auto service",
    "professional auto repair videos",
    "auto shop experience",
    "vehicle inspection process",
    "car repair overview",
    "auto service promotion",
    "everything auto experience",
    "why choose everything auto",
    "auto shop trust videos",
    "mechanic skill demonstration",
    "auto repair reliability",
    "engine performance testing",
    "brake repair tutorial",
    "everything auto new york",
    "auto service franklin square",
    "vehicle diagnostics tutorial",
    "mechanic shop franklin square",
    "auto repair nyc area",
    "everything auto testimonials",
    "customer satisfaction videos",
    "car engine repair demonstration",
    "auto care education",
    "franklin square car mechanic",
    "auto maintenance expert videos",
    "everything auto digital inspection",
    "shop tour everything auto",
    "auto maintenance walkthrough",
    "vehicle health inspection",
    "how to maintain your car",
    "engine troubleshooting video",
    "professional auto repair",
    "car diagnostic check video",
    "auto care customer stories",
    "everything auto behind scenes",
    "everything auto service center",
    "auto repair workshop video",
    "franklin square repair experts",
    "auto service demo",
    "auto shop success stories",
    "customer service excellence auto",
    "automotive maintenance guide",
    "car service explanation",
    "auto diagnostics explained video",
    "auto repair reliability demo",
    "auto repair professional service",
    "mechanic tools demo",
    "transparency in auto service",
    "car diagnostics walkaround",
    "everything auto honest repair",
    "customer experience franklin square",
    "auto shop visual tour",
    "professional car maintenance",
    "everything auto media",
    "mechanic expertise video",
    "franklin square repair shop",
    "auto shop excellence",
    "repair transparency everything auto",
    "auto repair workflow",
    "auto workshop behind scenes",
    "everything auto success story",
    "best auto repair franklin square",
    "everything auto certified technicians",
    "brake pad replacement video",
    "customer car repair story",
    "everything auto shop overview",
    "trusted auto mechanics",
    "everything auto maintenance advice",
    "auto care best practices",
    "car owner education video",
    "everything auto maintenance video",
    "transmission repair franklin square",
    "auto repair trust factor",
    "everything auto reliability",
    "customer experience stories",
    "auto mechanic insights",
    "car repair quality service",
    "everything auto 2025 videos",
    "auto repair marketing videos",
    "vehicle checkup guide",
    "everything auto long island",
    "car service insights",
    "auto repair vlog",
    "car owner testimonial",
    "auto repair daily operations",
    "engine performance check video",
    "vehicle service transparency",
    "auto maintenance reliability",
    "franklin square trusted mechanics",
    "auto repair tips and demos",
    "auto video marketing",
    "everything auto professional service",
    "customer experience repair shop",
    "everything auto demo videos",
    "auto repair digital inspection video",
    "everything auto auto repair tour",
    "vehicle diagnostics insight",
    "auto shop honesty videos",
    "auto repair real customers",
    "auto maintenance education",
    "everything auto service vlog",
    "car inspection clarity",
    "vehicle care demonstration",
    "engine repair explanation",
    "everything auto diagnostics center",
    "everything auto transparency policy",
    "auto repair visual content",
    "everything auto community",
    "car diagnostics explanation",
    "auto repair customer proof",
    "auto repair case study videos",
    "vehicle performance check",
    "auto maintenance awareness",
    "mechanic daily workflow",
    "everything auto trusted service",
    "auto maintenance habits",
    "vehicle care commitment",
    "everything auto how-to",
    "auto maintenance visual guide",
    "brake system explanation",
    "car inspection franklin square",
    "auto repair specialist franklin square",
    "everything auto diagnostics technology",
    "vehicle troubleshooting everything auto",
    "car diagnostics transparency",
    "mechanic shop process video",
    "vehicle repair confidence",
    "auto service how it works",
    "everything auto success video",
    "trusted car repair shop",
    "vehicle reliability process",
    "auto maintenance procedure",
    "mechanic expert interview",
    "car health check demo",
    "everything auto reliability test",
    "auto shop technology",
    "everything auto expertise",
    "auto repair client video",
    "mechanic training insight",
    "auto repair ny testimonials",
    "auto video documentation",
    "everything auto client success",
    "auto workshop visuals",
    "everything auto professional staff",
    "auto repair workflow tutorial",
    "vehicle care safety video",
    "everything auto long-term clients",
    "everything auto reputation",
    "car service tips",
    "auto repair learning",
    "customer focused auto shop",
    "everything auto repair education",
    "vehicle inspection quality",
    "everything auto brand story",
    "trusted mechanics new york",
    "auto diagnostic machine demo",
    "everything auto guide",
    "franklin square auto service videos",
    "vehicle maintenance transparency",
    "customer-focused auto care",
    "engine repair expertise",
    "everything auto excellence",
    "vehicle diagnostics process",
    "auto repair walkthroughs",
    "everything auto ny testimonial",
    "auto repair commitment",
    "vehicle repair knowledge",
    "everything auto training",
    "auto mechanic tools video",
    "car owner education everything auto",
    "auto shop overview everything auto",
    "everything auto technical video",
    "auto repair satisfaction stories",
    "car service reliability",
    "everything auto inspection guide",
    "auto service workshop franklin square",
    "car maintenance video gallery",
    "everything auto inspection process",
    "auto repair work process",
    "auto care insights",
    "mechanic video tutorial",
    "auto service awareness",
    "everything auto repair vlog",
    "auto transparency policy",
    "vehicle diagnostic analysis",
    "everything auto how we work",
    "trusted local auto shop",
    "everything auto car education",
    "auto care how-to guide",
    "everything auto professional team",
    "auto shop life videos",
    "vehicle repair stories",
    "everything auto customers",
    "everything auto mechanics",
    "auto maintenance repairs",
    "franklin square auto education",
    "auto repair behind scenes everything auto",
    "everything auto trusted results",
    "auto repair video explanation",
    "everything auto media gallery",
    "auto care customer experience",
    "auto shop education videos",
    "everything auto learning hub",
    "car maintenance vlog everything auto",
    "auto diagnostic step by step",
    "everything auto quality repair",
    "auto repair demonstration",
    "everything auto innovation",
    "auto service integrity",
    "everything auto high rating",
    "everything auto transparency videos",
    "everything auto tips and tutorials",
    "everything auto 5 star reviews",
    "car repair how it works",
    "everything auto digital reports",
    "auto repair digital media",
    "everything auto 2025 updates",
    "everything auto video hub",
    "car service testimonials 2025",
    "auto video series everything auto",
    "trusted auto service videos",
    "everything auto maintenance vlog",
    "everything auto youtube content",
    "vehicle inspection demonstration",
    "car repair testimonial franklin square",
    "everything auto shop walkthrough",
    "auto repair video center",
    "everything auto diagnostics overview",
    "auto repair new york videos",
    "everything auto customer trust",
    "auto service best shop",
    "car repair visuals",
    "auto repair honesty proof",
    "everything auto auto expertise",
    "auto repair daily tasks",
    "auto repair routine explanation",
    "everything auto innovation center",
    "vehicle health check video",
    "auto shop experience videos",
    "everything auto excellence proof",
    "auto repair results videos",
    "trusted auto experts",
    "everything auto long island shop",
    "everything auto genuine repairs",
    "vehicle transparency video",
    "everything auto franklin square ny",
    "auto maintenance culture videos",
    "car care experts videos",
    "everything auto workflow tour",
    "auto service visual proof",
    "auto diagnostics real footage",
    "everything auto client happiness"
  ],
};

export default async function Home() {
  return (
    <>
      <Videos />
    </>
  );
}
